# -*- coding: utf-8 -*-
"""HQIC

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qot_5u1i6WcQWlJmVZzUPri7eTLmkrHg
"""

import logging
import sys

def get_logger(name: str) -> logging.Logger:
    """Configures and returns a standard logger for the project."""
    logger = logging.getLogger(name)
    if not logger.handlers:
        logger.setLevel(logging.INFO)
        formatter = logging.Formatter(
            fmt='%(asctime)s | %(levelname)-8s | %(name)s | %(message)s',
            datefmt='%Y-%m-%d %H:%M:%S'
        )
        console_handler = logging.StreamHandler(sys.stdout)
        console_handler.setFormatter(formatter)
        logger.addHandler(console_handler)
    return logger

from dataclasses import dataclass
from typing import Tuple

@dataclass
class ModelConfig:
    """Centralized configuration for the Hybrid Quantum Model."""
    image_size: Tuple[int, int] = (64, 64)
    batch_size: int = 32
    learning_rate: float = 0.001
    epochs: int = 20
    n_qubits: int = 4
    n_quantum_layers: int = 2
    num_classes: int = 2
    data_dir: str = "/content/drive/MyDrive/Hybrid_Quantum_Image_Classifier/data/" # Updated path to Google Drive
    checkpoint_dir: str = "./assets/checkpoints/"

import torch
from torch.utils.data import DataLoader, Dataset
from torchvision import transforms, datasets

# ModelConfig and get_logger are defined in previous cells and are globally available.
# from config.settings import ModelConfig
# from utils.logger import get_logger

logger = get_logger(__name__)

class QuantumImageDataLoader:
    """Handles image preprocessing and data loading."""

    def __init__(self, config: ModelConfig):
        self.config = config
        self.transform = transforms.Compose([
            transforms.Resize(self.config.image_size),
            transforms.ToTensor(),
            transforms.Normalize(mean=[0.5], std=[0.5])
        ])

    def get_loaders(self) -> Tuple[DataLoader, DataLoader]:
        """Returns train and validation DataLoaders."""
        logger.info(f"Loading data from {self.config.data_dir}")
        # Insert your existing dataset logic here.
        # Example using ImageFolder:
        train_dataset = datasets.ImageFolder(f"{self.config.data_dir}/train", transform=self.transform)
        val_dataset = datasets.ImageFolder(f"{self.config.data_dir}/val", transform=self.transform)

        train_loader = DataLoader(train_dataset, batch_size=self.config.batch_size, shuffle=True)
        val_loader = DataLoader(val_dataset, batch_size=self.config.batch_size, shuffle=False)

        return train_loader, val_loader

import torch
import torch.nn as nn
# get_logger is defined in a previous cell and is globally available.
# from utils.logger import get_logger

logger = get_logger(__name__)

class ClassicalFeatureExtractor(nn.Module):
    """Classical CNN to reduce image dimensionality before the quantum circuit."""

    def __init__(self, output_dim: int):
        super().__init__()
        logger.info(f"Initializing ClassicalFeatureExtractor with output_dim={output_dim}")
        # Insert your existing CNN layers here
        self.network = nn.Sequential(
            nn.Conv2d(3, 16, kernel_size=3, stride=1, padding=1),
            nn.ReLU(),
            nn.MaxPool2d(2),
            nn.Flatten(),
            nn.Linear(16 * 32 * 32, output_dim) # Example dimensions
        )

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        return self.network(x)

import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader
# ModelConfig and get_logger are defined in previous cells and are globally available.
# from config.settings import ModelConfig
# from utils.logger import get_logger
import os

logger = get_logger(__name__)

class HybridModelTrainer:
    """Handles the training loop, loss computation, and checkpointing."""

    def __init__(self, model: nn.Module, config: ModelConfig):
        self.model = model
        self.config = config
        self.device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
        self.model.to(self.device)

        self.criterion = nn.CrossEntropyLoss()
        self.optimizer = optim.Adam(self.model.parameters(), lr=config.learning_rate)

        os.makedirs(self.config.checkpoint_dir, exist_ok=True)

    def train(self, train_loader: DataLoader, val_loader: DataLoader):
        logger.info(f"Starting training on device: {self.device}")

        for epoch in range(self.config.epochs):
            self.model.train()
            running_loss = 0.0

            for batch_idx, (inputs, targets) in enumerate(train_loader):
                inputs, targets = inputs.to(self.device), targets.to(self.device)

                self.optimizer.zero_grad()
                outputs = self.model(inputs)
                loss = self.criterion(outputs, targets)

                loss.backward()
                self.optimizer.step()
                running_loss += loss.item()

            avg_loss = running_loss / len(train_loader)
            logger.info(f"Epoch [{epoch+1}/{self.config.epochs}] - Loss: {avg_loss:.4f}")

            # Save checkpoint
            torch.save(self.model.state_dict(), f"{self.config.checkpoint_dir}/model_epoch_{epoch+1}.pt")

# 1. Mount Google Drive
from google.colab import drive
drive.mount('/content/drive')

# 2. Add the project directory to the Python path
import sys
project_path = '/content/drive/MyDrive/Hybrid_Quantum_Image_Classifier'
if project_path not in sys.path:
    sys.path.append(project_path)

# 3. Enable autoreload so changes made to .py files reflect immediately in the notebook
# %load_ext autoreload # Removed as 'imp' module is deprecated in Python 3.12
# %autoreload 2 # Removed as 'imp' module is deprecated in Python 3.12

# 4. Execute the pipeline
# ModelConfig, QuantumImageDataLoader, and HybridModelTrainer are defined in previous cells and are globally available.
# HybridQuantumClassifier is not yet defined in the notebook, so its import is commented out for now.
# from config.settings import ModelConfig
# from data.loader import QuantumImageDataLoader
# from models.hybrid.classifier import HybridQuantumClassifier
# from training.trainer import HybridModelTrainer

# Initialize Configuration
config = ModelConfig()

# Load Data
data_loader = QuantumImageDataLoader(config)
train_loader, val_loader = data_loader.get_loaders()

# Initialize Model
# model = HybridQuantumClassifier(config) # This class is not defined yet

# Train
trainer = HybridModelTrainer(None, config) # Pass None for model for now, as it's not defined
trainer.train(train_loader, val_loader)

print(f"Current config.data_dir: {config.data_dir}")

import os

# Get the data_dir from the config object (assuming config is still in scope)
data_dir_path = config.data_dir

print(f"Checking contents of: {data_dir_path}")

# Check if the base data directory exists
if not os.path.exists(data_dir_path):
    print(f"Error: Base data directory does not exist: {data_dir_path}")
elif not os.path.isdir(data_dir_path):
    print(f"Error: Base data path is not a directory: {data_dir_path}")
else:
    print(f"Contents of {data_dir_path}:")
    try:
        for item in os.listdir(data_dir_path):
            print(f"- {item}")
    except Exception as e:
        print(f"Could not list contents: {e}")

# Check specifically for 'train' and 'val' subdirectories
train_path = os.path.join(data_dir_path, 'train')
val_path = os.path.join(data_dir_path, 'val')

print(f"\nVerifying 'train' directory: {train_path}")
if os.path.exists(train_path):
    print(f"'train' directory exists. Is it a directory? {os.path.isdir(train_path)}")
    if os.path.isdir(train_path):
        try:
            train_contents = os.listdir(train_path)
            print(f"'train' directory contains {len(train_contents)} items (first 5): {train_contents[:5]}")
        except Exception as e:
            print(f"Could not list contents of 'train' directory: {e}")
else:
    print(f"'train' directory DOES NOT EXIST at: {train_path}")

print(f"\nVerifying 'val' directory: {val_path}")
if os.path.exists(val_path):
    print(f"'val' directory exists. Is it a directory? {os.path.isdir(val_path)}")
    if os.path.isdir(val_path):
        try:
            val_contents = os.listdir(val_path)
            print(f"'val' directory contains {len(val_contents)} items (first 5): {val_contents[:5]}")
        except Exception as e:
            print(f"Could not list contents of 'val' directory: {e}")
else:
    print(f"'val' directory DOES NOT EXIST at: {val_path}")

"""dataset"""

import os

directories = [
    "config",
    "data",
    "models/classical",
    "models/quantum",
    "models/hybrid",
    "training",
    "evaluation",
    "deployment",
    "utils",
    "visualization",
    "assets/checkpoints"
]

for directory in directories:
    os.makedirs(directory, exist_ok=True)

print("Modular directory structure initialized.")

# Commented out IPython magic to ensure Python compatibility.
# %%writefile utils/logger.py
# import logging
# import sys
# 
# def get_logger(name: str) -> logging.Logger:
#     """Configures and returns a standard logger for the project."""
#     logger = logging.getLogger(name)
#     if not logger.handlers:
#         logger.setLevel(logging.INFO)
#         formatter = logging.Formatter(
#             fmt='%(asctime)s | %(levelname)-8s | %(name)s | %(message)s',
#             datefmt='%Y-%m-%d %H:%M:%S'
#         )
#         console_handler = logging.StreamHandler(sys.stdout)
#         console_handler.setFormatter(formatter)
#         logger.addHandler(console_handler)
#     return logger

# Commented out IPython magic to ensure Python compatibility.
# %%writefile config/settings.py
# from dataclasses import dataclass
# from typing import Tuple
# 
# @dataclass
# class ModelConfig:
#     """Centralized configuration for the Hybrid Quantum Model."""
#     image_size: Tuple[int, int] = (64, 64)
#     batch_size: int = 32
#     learning_rate: float = 0.001
#     epochs: int = 20
#     n_qubits: int = 4
#     n_quantum_layers: int = 2
#     num_classes: int = 3  # Updated for Road, Sky, Rain
#     data_dir: str = "./data/"
#     checkpoint_dir: str = "./assets/checkpoints/"

# Commented out IPython magic to ensure Python compatibility.
# %%writefile data/loader.py
# import os
# from collections import Counter
# from pathlib import Path
# from typing import Callable, Dict, List, Optional, Tuple, Union
# 
# import torch
# from PIL import Image, UnidentifiedImageError
# from torch.utils.data import DataLoader, Dataset, WeightedRandomSampler
# from torchvision import transforms
# from tqdm import tqdm
# 
# from config.settings import ModelConfig
# from utils.logger import get_logger
# 
# logger = get_logger(__name__)
# 
# class RobustImageDataset(Dataset):
#     """
#     Custom PyTorch Dataset with image caching, corruption detection,
#     and class distribution tracking.
#     """
# 
#     SUPPORTED_FORMATS = {'.jpg', '.jpeg', '.png', '.bmp'}
# 
#     def __init__(self, root_dir: Union[str, Path], transform: Optional[Callable] = None):
#         self.root_dir = Path(root_dir)
#         self.transform = transform
# 
#         self.classes: List[str] = []
#         self.class_to_idx: Dict[str, int] = {}
#         self.samples: List[Tuple[Path, int]] = []
#         self.class_counts: Counter = Counter()
# 
#         if not self.root_dir.exists():
#             raise FileNotFoundError(f"Directory not found: {self.root_dir}")
# 
#         self._find_classes()
#         self._build_cache()
# 
#     def _find_classes(self) -> None:
#         """Scans the directory for class folders and creates mappings."""
#         classes = [d.name for d in self.root_dir.iterdir() if d.is_dir()]
#         self.classes = sorted(classes)
#         self.class_to_idx = {cls_name: i for i, cls_name in enumerate(self.classes)}
# 
#         if not self.classes:
#             raise ValueError(f"No class folders found in {self.root_dir}")
# 
#     def _build_cache(self) -> None:
#         """Caches valid image paths and automatically skips corrupt files."""
#         logger.info(f"Scanning and validating images in {self.root_dir}...")
# 
#         all_paths = []
#         for cls_name in self.classes:
#             cls_dir = self.root_dir / cls_name
#             for path in cls_dir.rglob('*'):
#                 if path.is_file() and path.suffix.lower() in self.SUPPORTED_FORMATS:
#                     all_paths.append((path, self.class_to_idx[cls_name], cls_name))
# 
#         valid_samples = []
#         corrupt_count = 0
# 
#         with tqdm(total=len(all_paths), desc=f"Validating {self.root_dir.name}", unit="img") as pbar:
#             for path, class_idx, cls_name in all_paths:
#                 if self._is_valid_image(path):
#                     valid_samples.append((path, class_idx))
#                     self.class_counts[cls_name] += 1
#                 else:
#                     corrupt_count += 1
#                 pbar.update(1)
# 
#         self.samples = valid_samples
# 
#         if corrupt_count > 0:
#             logger.warning(f"Ignored {corrupt_count} corrupt or unreadable images in {self.root_dir}.")
# 
#     @staticmethod
#     def _is_valid_image(path: Path) -> bool:
#         """Verifies if an image can be opened and is not corrupted."""
#         try:
#             with Image.open(path) as img:
#                 img.verify()
#             return True
#         except (IOError, SyntaxError, UnidentifiedImageError):
#             return False
# 
#     def __len__(self) -> int:
#         return len(self.samples)
# 
#     def __getitem__(self, idx: int) -> Tuple[torch.Tensor, int]:
#         path, class_idx = self.samples[idx]
# 
#         with Image.open(path) as img:
#             sample = img.convert('RGB')
# 
#         if self.transform:
#             sample = self.transform(sample)
# 
#         return sample, class_idx
# 
# 
# class QuantumImageDataLoader:
#     """Production data manager handling splits, balancing, and summaries."""
# 
#     def __init__(self, config: ModelConfig):
#         self.config = config
#         self.base_dir = Path(self.config.data_dir)
# 
#         self.transform = transforms.Compose([
#             transforms.Resize(self.config.image_size),
#             transforms.ToTensor(),
#             transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])
#         ])
# 
#     def _get_balanced_sampler(self, dataset: RobustImageDataset) -> WeightedRandomSampler:
#         """Calculates weights to handle class imbalance during training."""
#         class_weights = {
#             cls_name: 1.0 / count
#             for cls_name, count in dataset.class_counts.items()
#         }
# 
#         sample_weights = [
#             class_weights[dataset.classes[class_idx]]
#             for _, class_idx in dataset.samples
#         ]
# 
#         return WeightedRandomSampler(
#             weights=sample_weights,
#             num_samples=len(sample_weights),
#             replacement=True
#         )
# 
#     def _generate_summary(self, split_name: str, dataset: RobustImageDataset) -> None:
#         """Logs a formatted table of dataset statistics."""
#         logger.info(f"--- Dataset Summary: {split_name.upper()} ---")
#         logger.info(f"Total valid images: {len(dataset)}")
#         logger.info("Class Distribution:")
# 
#         for cls_name in dataset.classes:
#             count = dataset.class_counts[cls_name]
#             percentage = (count / len(dataset)) * 100 if len(dataset) > 0 else 0
#             logger.info(f"  - {cls_name:10s} : {count:5d} images ({percentage:5.1f}%)")
#         logger.info("-" * 35)
# 
#     def get_loaders(self) -> Tuple[DataLoader, DataLoader, Optional[DataLoader]]:
#         """Builds Train, Validation, and Test loaders."""
#         train_dir = self.base_dir / "train"
#         val_dir = self.base_dir / "val"
#         test_dir = self.base_dir / "test"
# 
#         logger.info("Initializing Training Dataset...")
#         train_dataset = RobustImageDataset(train_dir, transform=self.transform)
#         self._generate_summary("Train", train_dataset)
# 
#         train_sampler = self._get_balanced_sampler(train_dataset)
#         train_loader = DataLoader(
#             train_dataset, batch_size=self.config.batch_size,
#             sampler=train_sampler, num_workers=2, pin_memory=True
#         )
# 
#         logger.info("Initializing Validation Dataset...")
#         val_dataset = RobustImageDataset(val_dir, transform=self.transform)
#         self._generate_summary("Validation", val_dataset)
# 
#         val_loader = DataLoader(
#             val_dataset, batch_size=self.config.batch_size,
#             shuffle=False, num_workers=2, pin_memory=True
#         )
# 
#         test_loader = None
#         if test_dir.exists():
#             logger.info("Initializing Test Dataset...")
#             test_dataset = RobustImageDataset(test_dir, transform=self.transform)
#             self._generate_summary("Test", test_dataset)
# 
#             test_loader = DataLoader(
#                 test_dataset, batch_size=self.config.batch_size,
#                 shuffle=False, num_workers=2, pin_memory=True
#             )
# 
#         return train_loader, val_loader, test_loader

# Commented out IPython magic to ensure Python compatibility.
# %%writefile models/classical/feature_extractor.py
# import torch
# import torch.nn as nn
# from utils.logger import get_logger
# 
# logger = get_logger(__name__)
# 
# class ClassicalFeatureExtractor(nn.Module):
#     """Classical CNN to reduce image dimensionality before the quantum circuit."""
# 
#     def __init__(self, output_dim: int):
#         super().__init__()
#         logger.info(f"Initializing ClassicalFeatureExtractor with output_dim={output_dim}")
# 
#         self.network = nn.Sequential(
#             nn.Conv2d(3, 16, kernel_size=3, stride=1, padding=1),
#             nn.ReLU(),
#             nn.MaxPool2d(2),
#             nn.Flatten(),
#             nn.Linear(16 * 32 * 32, output_dim)
#         )
# 
#     def forward(self, x: torch.Tensor) -> torch.Tensor:
#         return self.network(x)

# Commented out IPython magic to ensure Python compatibility.
# %%writefile models/quantum/circuit.py
# import torch
# import torch.nn as nn
# from config.settings import ModelConfig
# from utils.logger import get_logger
# 
# logger = get_logger(__name__)
# 
# class VariationalQuantumCircuit(nn.Module):
#     """VQC Layer wrapped as a PyTorch module."""
# 
#     def __init__(self, config: ModelConfig):
#         super().__init__()
#         self.n_qubits = config.n_qubits
#         logger.info(f"Initializing VQC with {self.n_qubits} qubits.")
# 
#         # INSERT PENNYLANE/QISKIT QNODE HERE
#         self.q_layer = None
# 
#     def forward(self, x: torch.Tensor) -> torch.Tensor:
#         # Pass features through the quantum node
#         return self.q_layer(x) if self.q_layer else x

# Commented out IPython magic to ensure Python compatibility.
# %%writefile models/hybrid/classifier.py
# import torch
# import torch.nn as nn
# from models.classical.feature_extractor import ClassicalFeatureExtractor
# from models.quantum.circuit import VariationalQuantumCircuit
# from config.settings import ModelConfig
# 
# class HybridQuantumClassifier(nn.Module):
#     """Combines classical feature extraction with quantum classification."""
# 
#     def __init__(self, config: ModelConfig):
#         super().__init__()
#         self.feature_extractor = ClassicalFeatureExtractor(output_dim=config.n_qubits)
#         self.quantum_circuit = VariationalQuantumCircuit(config)
#         self.classifier = nn.Linear(config.n_qubits, config.num_classes)
# 
#     def forward(self, x: torch.Tensor) -> torch.Tensor:
#         x = self.feature_extractor(x)
#         x = self.quantum_circuit(x)
#         x = self.classifier(x)
#         return x

# Commented out IPython magic to ensure Python compatibility.
# %%writefile training/trainer.py
# import os
# import torch
# import torch.nn as nn
# import torch.optim as optim
# from torch.utils.data import DataLoader
# from config.settings import ModelConfig
# from utils.logger import get_logger
# 
# logger = get_logger(__name__)
# 
# class HybridModelTrainer:
#     """Handles the training loop, loss computation, and checkpointing."""
# 
#     def __init__(self, model: nn.Module, config: ModelConfig):
#         self.model = model
#         self.config = config
#         self.device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
#         self.model.to(self.device)
# 
#         self.criterion = nn.CrossEntropyLoss()
#         self.optimizer = optim.Adam(self.model.parameters(), lr=config.learning_rate)
# 
#         os.makedirs(self.config.checkpoint_dir, exist_ok=True)
# 
#     def train(self, train_loader: DataLoader, val_loader: DataLoader):
#         logger.info(f"Starting training on device: {self.device}")
# 
#         for epoch in range(self.config.epochs):
#             self.model.train()
#             running_loss = 0.0
# 
#             for batch_idx, (inputs, targets) in enumerate(train_loader):
#                 inputs, targets = inputs.to(self.device), targets.to(self.device)
# 
#                 self.optimizer.zero_grad()
#                 outputs = self.model(inputs)
#                 loss = self.criterion(outputs, targets)
# 
#                 loss.backward()
#                 self.optimizer.step()
#                 running_loss += loss.item()
# 
#             avg_loss = running_loss / len(train_loader)
#             logger.info(f"Epoch [{epoch+1}/{self.config.epochs}] - Loss: {avg_loss:.4f}")
# 
#             torch.save(
#                 self.model.state_dict(),
#                 f"{self.config.checkpoint_dir}/model_epoch_{epoch+1}.pt"
#             )

import sys

# Ensure Colab recognizes the newly created file structure as importable modules
if '.' not in sys.path:
    sys.path.append('.')

from config.settings import ModelConfig
from data.loader import QuantumImageDataLoader
from models.hybrid.classifier import HybridQuantumClassifier
from training.trainer import HybridModelTrainer

# 1. Initialize Configuration
config = ModelConfig()

# Optional: Create dummy data folders for testing execution if data doesn't exist yet
import os
for split in ['train', 'val']:
    for cls in ['Road', 'Sky', 'Rain']:
        os.makedirs(f"./data/{split}/{cls}", exist_ok=True)

try:
    # 2. Load Data
    data_loader = QuantumImageDataLoader(config)
    train_loader, val_loader, test_loader = data_loader.get_loaders()

    # 3. Initialize Model
    model = HybridQuantumClassifier(config)

    # 4. Train
    trainer = HybridModelTrainer(model, config)
    trainer.train(train_loader, val_loader)
except ValueError as e:
    print(f"\n[!] Data Loading Halted: {e}")
    print("Please populate the './data/train' and './data/val' folders with your images.")

"""# preprocessing"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile data/preprocessing.py
# import cv2
# import numpy as np
# import torch
# import torchvision.transforms.v2 as v2
# from PIL import Image
# from typing import Tuple
# 
# class AdvancedPhotometricEnhancement:
#     """
#     Applies Contrast Limited Adaptive Histogram Equalization (CLAHE)
#     and Gamma Correction to enhance image features (edges, shadows)
#     before quantum encoding.
#     """
#     def __init__(self, clip_limit: float = 2.0, tile_grid_size: Tuple[int, int] = (8, 8), gamma: float = 1.2):
#         self.clip_limit = clip_limit
#         self.tile_grid_size = tile_grid_size
#         self.gamma = gamma
# 
#     def __call__(self, img: Image.Image) -> Image.Image:
#         # Convert PIL to NumPy
#         img_np = np.array(img)
# 
#         # Apply CLAHE on the L-channel of LAB color space to preserve colors
#         lab = cv2.cvtColor(img_np, cv2.COLOR_RGB2LAB)
#         l, a, b = cv2.split(lab)
# 
#         clahe = cv2.createCLAHE(clipLimit=self.clip_limit, tileGridSize=self.tile_grid_size)
#         cl = clahe.apply(l)
# 
#         limg = cv2.merge((cl, a, b))
#         img_clahe = cv2.cvtColor(limg, cv2.COLOR_LAB2RGB)
# 
#         # Apply Gamma Correction
#         inv_gamma = 1.0 / self.gamma
#         table = np.array([((i / 255.0) ** inv_gamma) * 255 for i in np.arange(0, 256)]).astype("uint8")
#         img_gamma = cv2.LUT(img_clahe, table)
# 
#         return Image.fromarray(img_gamma)
# 
# 
# class QuantumPreprocessor:
#     """
#     Production-grade preprocessing pipeline optimized for batched tensor
#     operations and Automatic Mixed Precision (AMP) compatibility.
#     """
# 
#     # Standard ImageNet Statistics
#     IMAGENET_MEAN = [0.485, 0.456, 0.406]
#     IMAGENET_STD = [0.229, 0.224, 0.225]
# 
#     def __init__(self, image_size: Tuple[int, int] = (64, 64)):
#         self.image_size = image_size
# 
#     def get_train_transforms(self) -> v2.Compose:
#         """
#         Aggressive augmentation pipeline for training.
#         Uses torchvision.transforms.v2 for batch optimization.
#         """
#         return v2.Compose([
#             # 1. Base Setup
#             v2.Resize(self.image_size, interpolation=v2.InterpolationMode.BILINEAR, antialias=True),
# 
#             # 2. Photometric Adjustments (CLAHE & Gamma)
#             AdvancedPhotometricEnhancement(clip_limit=2.0, gamma=1.2),
# 
#             # 3. Geometric & Color Augmentations
#             v2.RandomPerspective(distortion_scale=0.3, p=0.4),
#             v2.ColorJitter(brightness=0.2, contrast=0.2, saturation=0.2, hue=0.1),
#             v2.GaussianBlur(kernel_size=(3, 5), sigma=(0.1, 2.0)),
# 
#             # 4. Tensor Conversion (Creates float32 tensors, ideal for AMP casting downstream)
#             v2.ToImage(),
#             v2.ToDtype(torch.float32, scale=True),
# 
#             # 5. Normalization
#             v2.Normalize(mean=self.IMAGENET_MEAN, std=self.IMAGENET_STD),
# 
#             # 6. Denoising/Regularization (Random Erasing must be applied to Tensors)
#             v2.RandomErasing(p=0.3, scale=(0.02, 0.2), ratio=(0.3, 3.3), value='random')
#         ])
# 
#     def get_val_transforms(self) -> v2.Compose:
#         """
#         Clean, deterministic pipeline for Validation/Testing.
#         """
#         return v2.Compose([
#             # 1. Base Setup
#             v2.Resize(self.image_size, interpolation=v2.InterpolationMode.BILINEAR, antialias=True),
# 
#             # 2. Photometric Adjustments (Must match training state)
#             AdvancedPhotometricEnhancement(clip_limit=2.0, gamma=1.2),
# 
#             # 3. Tensor Conversion
#             v2.ToImage(),
#             v2.ToDtype(torch.float32, scale=True),
# 
#             # 4. Normalization
#             v2.Normalize(mean=self.IMAGENET_MEAN, std=self.IMAGENET_STD)
#         ])

"""# CNN Feature"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile models/classical/feature_extractor.py
# import torch
# import torch.nn as nn
# import torchvision.models as models
# from typing import Optional
# from utils.logger import get_logger
# 
# logger = get_logger(__name__)
# 
# class ClassicalFeatureExtractor(nn.Module):
#     """
#     Robust classical feature extractor serving as the front-end for the
#     Hybrid Quantum Classifier. Reduces high-dimensional images down to
#     the exact number of qubits required for quantum encoding.
#     """
# 
#     SUPPORTED_BACKBONES = {
#         'resnet50',
#         'efficientnet_b0',
#         'efficientnet_v2_s',
#         'convnext_tiny',
#         'mobilenet_v3'
#     }
# 
#     def __init__(self, output_dim: int, backbone_name: str = 'resnet50', dropout_rate: float = 0.3):
#         """
#         Initializes the feature extractor.
# 
#         Args:
#             output_dim: The target dimension matching `config.n_qubits`.
#             backbone_name: The CNN architecture to load (can be passed from config).
#             dropout_rate: Regularization rate before the final linear projection.
#         """
#         super().__init__()
#         self.backbone_name = backbone_name.lower()
#         self.output_dim = output_dim
# 
#         if self.backbone_name not in self.SUPPORTED_BACKBONES:
#             raise ValueError(f"Backbone '{self.backbone_name}' not supported. Choose from {self.SUPPORTED_BACKBONES}")
# 
#         logger.info(f"Initializing {self.backbone_name.upper()} as Classical Feature Extractor...")
#         self.backbone = self._build_backbone()
# 
#         # 1. Automatically freeze backbone layers for Transfer Learning
#         self._freeze_backbone()
# 
#         # 2. Dynamically determine in_features for the reduction head
#         in_features = self._get_feature_dim()
#         logger.info(f"Backbone flattened feature dimension detected as: {in_features}")
# 
#         # 3. Build the highly regularized reduction head
#         self.reduction_head = nn.Sequential(
#             nn.BatchNorm1d(in_features),
#             nn.Dropout(p=dropout_rate),
#             nn.Linear(in_features, self.output_dim),
#             # Tanh bounds outputs to [-1, 1], making them perfectly formatted
#             # for stable Quantum Angle Encoding (e.g., Ry, Rx gates)
#             nn.Tanh()
#         )
# 
#     def _build_backbone(self) -> nn.Module:
#         """Loads pretrained weights and strips the classification head."""
#         if self.backbone_name == 'resnet50':
#             model = models.resnet50(weights=models.ResNet50_Weights.DEFAULT)
#             model.fc = nn.Identity()
# 
#         elif self.backbone_name == 'efficientnet_b0':
#             model = models.efficientnet_b0(weights=models.EfficientNet_B0_Weights.DEFAULT)
#             model.classifier = nn.Identity()
# 
#         elif self.backbone_name == 'efficientnet_v2_s':
#             model = models.efficientnet_v2_s(weights=models.EfficientNet_V2_S_Weights.DEFAULT)
#             model.classifier = nn.Identity()
# 
#         elif self.backbone_name == 'convnext_tiny':
#             model = models.convnext_tiny(weights=models.ConvNeXt_Tiny_Weights.DEFAULT)
#             model.classifier = nn.Identity()
# 
#         elif self.backbone_name == 'mobilenet_v3':
#             model = models.mobilenet_v3_large(weights=models.MobileNet_V3_Large_Weights.DEFAULT)
#             model.classifier = nn.Identity()
# 
#         return model
# 
#     def _freeze_backbone(self) -> None:
#         """Freezes all parameters in the backbone network."""
#         for param in self.backbone.parameters():
#             param.requires_grad = False
#         logger.info("Backbone layers frozen successfully.")
# 
#     def _get_feature_dim(self) -> int:
#         """Passes a dummy tensor to securely extract the exact intermediate feature dimension."""
#         dummy_input = torch.randn(1, 3, 64, 64)
# 
#         # Suppress gradient tracking for memory efficiency during initialization
#         with torch.no_grad():
#             out = self.backbone(dummy_input)
#             out = torch.flatten(out, 1)
# 
#         return out.shape[1]
# 
#     def forward(self, x: torch.Tensor) -> torch.Tensor:
#         """
#         Forward pass converting batched images into quantum-ready state vectors.
#         """
#         x = self.backbone(x)
#         # Handle architectures that output (B, C, 1, 1) feature maps natively
#         x = torch.flatten(x, 1)
#         x = self.reduction_head(x)
#         return x

"""Feature Reduction

"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile models/classical/feature_extractor.py
# import torch
# import torch.nn as nn
# import torchvision.models as models
# from typing import List, Optional
# from utils.logger import get_logger
# 
# logger = get_logger(__name__)
# 
# class ResidualLinearBlock(nn.Module):
#     """
#     A single block for feature reduction featuring a residual connection,
#     configurable normalization (BatchNorm/LayerNorm), and Dropout.
#     """
#     def __init__(self, in_dim: int, out_dim: int, dropout_rate: float, norm_type: str):
#         super().__init__()
#         self.fc = nn.Linear(in_dim, out_dim)
# 
#         if norm_type == 'batch':
#             self.norm = nn.BatchNorm1d(out_dim)
#         elif norm_type == 'layer':
#             self.norm = nn.LayerNorm(out_dim)
#         else:
#             raise ValueError(f"Unsupported norm_type: {norm_type}. Use 'batch' or 'layer'.")
# 
#         self.activation = nn.GELU()
#         self.dropout = nn.Dropout(dropout_rate)
# 
#         # Linear projection for the residual shortcut if dimensions change
#         self.shortcut = nn.Identity() if in_dim == out_dim else nn.Linear(in_dim, out_dim, bias=False)
# 
#     def forward(self, x: torch.Tensor) -> torch.Tensor:
#         residual = self.shortcut(x)
#         out = self.fc(x)
#         out = self.norm(out)
#         out = out + residual  # Add residual before activation
#         out = self.activation(out)
#         out = self.dropout(out)
#         return out
# 
# 
# class FeatureReductionHead(nn.Module):
#     """
#     Configurable module to reduce high-dimensional classical features
#     down to the exact number of qubits required for quantum encoding.
#     Example: 2048 -> 256 -> 64 -> 4
#     """
#     def __init__(
#         self,
#         in_features: int,
#         out_features: int,
#         hidden_dims: List[int],
#         dropout_rate: float = 0.3,
#         norm_type: str = 'layer'
#     ):
#         super().__init__()
#         logger.info(f"Building Reduction Head: {in_features} -> {hidden_dims} -> {out_features}")
# 
#         layers = []
#         current_dim = in_features
# 
#         # Build residual hidden layers dynamically
#         for h_dim in hidden_dims:
#             layers.append(ResidualLinearBlock(current_dim, h_dim, dropout_rate, norm_type))
#             current_dim = h_dim
# 
#         self.blocks = nn.Sequential(*layers)
# 
#         # Final projection to quantum embedding space
#         self.final_norm = nn.BatchNorm1d(current_dim) if norm_type == 'batch' else nn.LayerNorm(current_dim)
#         self.final_fc = nn.Linear(current_dim, out_features)
# 
#         # Tanh bounds outputs to [-1, 1] for stable Quantum Angle Encoding
#         self.final_act = nn.Tanh()
# 
#         self._initialize_weights()
# 
#     def _initialize_weights(self) -> None:
#         """Applies Kaiming Normal initialization to linear layers."""
#         for m in self.modules():
#             if isinstance(m, nn.Linear):
#                 nn.init.kaiming_normal_(m.weight, nonlinearity='linear')
#                 if m.bias is not None:
#                     nn.init.constant_(m.bias, 0)
#         logger.info("Applied Kaiming Normal weight initialization to Reduction Head.")
# 
#     def forward(self, x: torch.Tensor) -> torch.Tensor:
#         x = self.blocks(x)
#         x = self.final_norm(x)
#         x = self.final_fc(x)
#         return self.final_act(x)
# 
# 
# class ClassicalFeatureExtractor(nn.Module):
#     """
#     Robust classical feature extractor serving as the front-end for the
#     Hybrid Quantum Classifier.
#     """
# 
#     SUPPORTED_BACKBONES = {
#         'resnet50',
#         'efficientnet_b0',
#         'efficientnet_v2_s',
#         'convnext_tiny',
#         'mobilenet_v3'
#     }
# 
#     def __init__(
#         self,
#         output_dim: int,
#         backbone_name: str = 'resnet50',
#         hidden_dims: Optional[List[int]] = None,
#         dropout_rate: float = 0.3,
#         norm_type: str = 'layer'
#     ):
#         """
#         Initializes the feature extractor.
# 
#         Args:
#             output_dim: The target dimension matching `config.n_qubits`.
#             backbone_name: The CNN architecture to load.
#             hidden_dims: Dimensions of intermediate reduction layers (e.g., [256, 64]).
#             dropout_rate: Regularization rate for the reduction head.
#             norm_type: Normalization strategy ('batch' or 'layer').
#         """
#         super().__init__()
#         self.backbone_name = backbone_name.lower()
#         self.output_dim = output_dim
# 
#         # Default architecture for smooth step-down if not specified
#         if hidden_dims is None:
#             hidden_dims = [256, 64]
# 
#         if self.backbone_name not in self.SUPPORTED_BACKBONES:
#             raise ValueError(f"Backbone '{self.backbone_name}' not supported. Choose from {self.SUPPORTED_BACKBONES}")
# 
#         logger.info(f"Initializing {self.backbone_name.upper()} as Classical Feature Extractor...")
#         self.backbone = self._build_backbone()
# 
#         # Automatically freeze backbone layers for Transfer Learning
#         self._freeze_backbone()
# 
#         # Dynamically determine in_features for the reduction head
#         in_features = self._get_feature_dim()
#         logger.info(f"Backbone flattened feature dimension detected as: {in_features}")
# 
#         # Build the heavily regularized, residual reduction head
#         self.reduction_head = FeatureReductionHead(
#             in_features=in_features,
#             out_features=self.output_dim,
#             hidden_dims=hidden_dims,
#             dropout_rate=dropout_rate,
#             norm_type=norm_type
#         )
# 
#     def _build_backbone(self) -> nn.Module:
#         """Loads pretrained weights and strips the classification head."""
#         if self.backbone_name == 'resnet50':
#             model = models.resnet50(weights=models.ResNet50_Weights.DEFAULT)
#             model.fc = nn.Identity()
# 
#         elif self.backbone_name == 'efficientnet_b0':
#             model = models.efficientnet_b0(weights=models.EfficientNet_B0_Weights.DEFAULT)
#             model.classifier = nn.Identity()
# 
#         elif self.backbone_name == 'efficientnet_v2_s':
#             model = models.efficientnet_v2_s(weights=models.EfficientNet_V2_S_Weights.DEFAULT)
#             model.classifier = nn.Identity()
# 
#         elif self.backbone_name == 'convnext_tiny':
#             model = models.convnext_tiny(weights=models.ConvNeXt_Tiny_Weights.DEFAULT)
#             model.classifier = nn.Identity()
# 
#         elif self.backbone_name == 'mobilenet_v3':
#             model = models.mobilenet_v3_large(weights=models.MobileNet_V3_Large_Weights.DEFAULT)
#             model.classifier = nn.Identity()
# 
#         return model
# 
#     def _freeze_backbone(self) -> None:
#         """Freezes all parameters in the backbone network."""
#         for param in self.backbone.parameters():
#             param.requires_grad = False
#         logger.info("Backbone layers frozen successfully.")
# 
#     def _get_feature_dim(self) -> int:
#         """Passes a dummy tensor to securely extract the exact intermediate feature dimension."""
#         dummy_input = torch.randn(1, 3, 64, 64)
# 
#         with torch.no_grad():
#             out = self.backbone(dummy_input)
#             out = torch.flatten(out, 1)
# 
#         return out.shape[1]
# 
#     def forward(self, x: torch.Tensor) -> torch.Tensor:
#         """
#         Forward pass converting batched images into quantum-ready state vectors.
#         """
#         x = self.backbone(x)
#         x = torch.flatten(x, 1)
#         x = self.reduction_head(x)
#         return x

"""Ouantum Circuit

"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile models/quantum/circuit.py
# import math
# from typing import Any, Dict, Optional, Tuple
# 
# import torch
# import torch.nn as nn
# from utils.logger import get_logger
# 
# # Import PennyLane safely
# try:
#     import pennylane as qml
# except ImportError:
#     raise ImportError("PennyLane is required. Please run: pip install pennylane")
# 
# logger = get_logger(__name__)
# 
# class VariationalQuantumCircuit(nn.Module):
#     """
#     Advanced Configurable Quantum Circuit using PennyLane.
#     Supports dynamic embeddings, multiple ansätze, and automatic hardware selection.
#     """
# 
#     SUPPORTED_EMBEDDINGS = {'angle', 'amplitude', 'iqp'}
#     SUPPORTED_ANSATZES = {'strongly_entangling', 'basic', 'hardware_efficient'}
# 
#     def __init__(self, config: Any):
#         super().__init__()
# 
#         # 1. Parse configuration with safe defaults
#         self.n_qubits = getattr(config, 'n_qubits', 4)
#         self.n_layers = getattr(config, 'n_quantum_layers', 2)
#         self.embedding_type = getattr(config, 'embedding_type', 'angle').lower()
#         self.ansatz_type = getattr(config, 'ansatz_type', 'strongly_entangling').lower()
#         self.backend_name = getattr(config, 'backend_name', 'default.qubit').lower()
# 
#         if not (4 <= self.n_qubits <= 12):
#             logger.warning(f"Qubit count {self.n_qubits} is outside the recommended 4-12 range.")
# 
#         if self.embedding_type not in self.SUPPORTED_EMBEDDINGS:
#             raise ValueError(f"Unsupported embedding: {self.embedding_type}. Use {self.SUPPORTED_EMBEDDINGS}")
# 
#         if self.ansatz_type not in self.SUPPORTED_ANSATZES:
#             raise ValueError(f"Unsupported ansatz: {self.ansatz_type}. Use {self.SUPPORTED_ANSATZES}")
# 
#         # 2. Initialize Quantum Device automatically
#         self.dev = self._initialize_device()
# 
#         # 3. Determine Trainable Parameter Shapes
#         self.weight_shapes = self._get_weight_shapes()
# 
#         # 4. Construct the QNode
#         self.qnode = qml.QNode(self._circuit, self.dev, interface="torch")
# 
#         # 5. Wrap QNode in a PyTorch Layer
#         self.q_layer = qml.qnn.TorchLayer(self.qnode, self.weight_shapes)
# 
#         logger.info(f"Initialized VQC: {self.n_qubits} Qubits | "
#                     f"Embedding: {self.embedding_type} | Ansatz: {self.ansatz_type}")
# 
#     def _initialize_device(self) -> qml.Device:
#         """Selects the optimal execution backend (CPU Simulator, GPU, or IBM Q)."""
#         logger.info(f"Attempting to initialize quantum backend: {self.backend_name}")
#         try:
#             if self.backend_name == 'lightning.qubit':
#                 # Fast C++ based simulator
#                 return qml.device("lightning.qubit", wires=self.n_qubits)
# 
#             elif self.backend_name == 'ibmq':
#                 # Requires pennylane-qiskit plugin and IBMQ account configured
#                 return qml.device("qiskit.ibmq", wires=self.n_qubits, backend="ibmq_qasm_simulator")
# 
#         except Exception as e:
#             logger.warning(f"Failed to load {self.backend_name}: {e}. Falling back to default.qubit.")
# 
#         return qml.device("default.qubit", wires=self.n_qubits)
# 
#     def _get_weight_shapes(self) -> Dict[str, Tuple[int, ...]]:
#         """Calculates the exact tensor shapes needed for the chosen ansatz."""
#         if self.ansatz_type == 'strongly_entangling':
#             return {"weights": (self.n_layers, self.n_qubits, 3)}
#         elif self.ansatz_type == 'basic':
#             return {"weights": (self.n_layers, self.n_qubits)}
#         elif self.ansatz_type == 'hardware_efficient':
#             # shape: (layers, qubits, 2) for RY and RZ rotations
#             return {"weights": (self.n_layers, self.n_qubits, 2)}
#         return {}
# 
#     def _apply_embedding(self, inputs: torch.Tensor) -> None:
#         """Encodes classical data into the quantum state."""
#         if self.embedding_type == 'angle':
#             qml.AngleEmbedding(inputs, wires=range(self.n_qubits), rotation='Y')
# 
#         elif self.embedding_type == 'amplitude':
#             # Normalize and pad automatically if input < 2^N features
#             qml.AmplitudeEmbedding(inputs, wires=range(self.n_qubits), normalize=True, pad_with=0.0)
# 
#         elif self.embedding_type == 'iqp':
#             qml.IQPEmbedding(inputs, wires=range(self.n_qubits), n_repeats=2)
# 
#     def _apply_ansatz(self, weights: torch.Tensor) -> None:
#         """Applies the trainable variational layers."""
#         if self.ansatz_type == 'strongly_entangling':
#             qml.StronglyEntanglingLayers(weights, wires=range(self.n_qubits))
# 
#         elif self.ansatz_type == 'basic':
#             qml.BasicEntanglerLayers(weights, wires=range(self.n_qubits))
# 
#         elif self.ansatz_type == 'hardware_efficient':
#             # Custom implementation of a Hardware Efficient Ansatz
#             for layer in range(self.n_layers):
#                 for i in range(self.n_qubits):
#                     qml.RY(weights[layer, i, 0], wires=i)
#                     qml.RZ(weights[layer, i, 1], wires=i)
#                 # Linear entanglement map
#                 for i in range(self.n_qubits - 1):
#                     qml.CNOT(wires=[i, i + 1])
#                 # Ring connection if > 2 qubits
#                 if self.n_qubits > 2:
#                     qml.CNOT(wires=[self.n_qubits - 1, 0])
# 
#     def _circuit(self, inputs: torch.Tensor, weights: torch.Tensor) -> List[Any]:
#         """The core quantum function defining the QNode."""
#         self._apply_embedding(inputs)
#         self._apply_ansatz(weights)
# 
#         # Return PauliZ expectations for all qubits
#         return [qml.expval(qml.PauliZ(wires=i)) for i in range(self.n_qubits)]
# 
#     def forward(self, x: torch.Tensor) -> torch.Tensor:
#         """Executes the quantum circuit layer on batched classical tensors."""
#         return self.q_layer(x)
# 
#     def print_circuit_statistics(self) -> None:
#         """Generates and logs the circuit topology, depth, and parameter count."""
#         logger.info("--- Quantum Circuit Statistics ---")
# 
#         # Generate dummy inputs to trace the circuit
#         dummy_inputs = torch.rand(self.n_qubits)
#         if self.embedding_type == 'amplitude':
#             dummy_inputs = torch.rand(2 ** self.n_qubits)
# 
#         dummy_weights = torch.rand(self.weight_shapes["weights"])
# 
#         # 1. Print Trainable Parameters
#         total_params = math.prod(self.weight_shapes["weights"])
#         logger.info(f"Total Trainable Quantum Parameters: {total_params}")
# 
#         # 2. Get Circuit Specifications (including Depth)
#         specs = qml.specs(self.qnode)(dummy_inputs, dummy_weights)
#         logger.info(f"Circuit Depth: {specs['depth']}")
#         logger.info(f"Gate Count: {specs['num_operations']}")
# 
#         # 3. Draw Circuit
#         try:
#             drawer = qml.draw(self.qnode, max_length=120)
#             drawn_circuit = drawer(dummy_inputs, dummy_weights)
#             print(f"\nCircuit Architecture:\n{drawn_circuit}\n")
#         except Exception as e:
#             logger.warning(f"Could not draw circuit: {e}")

"""Hybrid Model"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile models/hybrid/classifier.py
# from typing import List, Optional
# 
# import torch
# import torch.nn as nn
# 
# from config.settings import ModelConfig
# from models.classical.feature_extractor import ClassicalFeatureExtractor
# from models.quantum.circuit import VariationalQuantumCircuit
# from utils.logger import get_logger
# 
# logger = get_logger(__name__)
# 
# class FeatureAttentionBlock(nn.Module):
#     """
#     1D Self-Attention mechanism applied to classical features before quantum encoding.
#     Utilizes LayerNorm, Dropout, and Residual Connections to refine the feature
#     representation prior to parameterized quantum circuit embedding.
#     """
#     def __init__(self, embed_dim: int, dropout: float = 0.1):
#         super().__init__()
#         # num_heads=1 ensures compatibility with any n_qubits dimension (e.g., 4, 10)
#         self.attention = nn.MultiheadAttention(
#             embed_dim, num_heads=1, dropout=dropout, batch_first=True
#         )
#         self.norm1 = nn.LayerNorm(embed_dim)
#         self.norm2 = nn.LayerNorm(embed_dim)
# 
#         # Feed-forward network (FFN)
#         self.ffn = nn.Sequential(
#             nn.Linear(embed_dim, embed_dim * 2),
#             nn.GELU(),
#             nn.Dropout(dropout),
#             nn.Linear(embed_dim * 2, embed_dim)
#         )
#         self.dropout = nn.Dropout(dropout)
# 
#     def forward(self, x: torch.Tensor) -> torch.Tensor:
#         # Reshape to (Batch, Sequence=1, Embedding=n_qubits)
#         x_seq = x.unsqueeze(1)
# 
#         # Self-Attention + Residual 1 + LayerNorm
#         attn_out, _ = self.attention(x_seq, x_seq, x_seq)
#         x_seq = self.norm1(x_seq + self.dropout(attn_out))
# 
#         # FFN + Residual 2 + LayerNorm
#         ffn_out = self.ffn(x_seq)
#         x_seq = self.norm2(x_seq + self.dropout(ffn_out))
# 
#         # Revert to (Batch, Embedding)
#         return x_seq.squeeze(1)
# 
# 
# class FlexibleClassifierHead(nn.Module):
#     """
#     Configurable classification head with LayerNorm, GELU, and Dropout.
#     Dynamically builds hidden layers based on the requested architecture.
#     """
#     def __init__(
#         self,
#         in_features: int,
#         num_classes: int,
#         hidden_dims: Optional[List[int]] = None,
#         dropout: float = 0.3
#     ):
#         super().__init__()
# 
#         if hidden_dims is None:
#             # Default to one intermediate layer scaling down smoothly
#             hidden_dims = [in_features // 2] if in_features > 4 else []
# 
#         layers = []
#         current_dim = in_features
# 
#         for h_dim in hidden_dims:
#             if h_dim > 0:
#                 layers.extend([
#                     nn.Linear(current_dim, h_dim),
#                     nn.LayerNorm(h_dim),
#                     nn.GELU(),
#                     nn.Dropout(dropout)
#                 ])
#                 current_dim = h_dim
# 
#         # Final classification projection
#         layers.append(nn.Linear(current_dim, num_classes))
#         self.head = nn.Sequential(*layers)
# 
#     def forward(self, x: torch.Tensor) -> torch.Tensor:
#         return self.head(x)
# 
# 
# class HybridQuantumClassifier(nn.Module):
#     """
#     Advanced Hybrid Model integrating classical CNNs, self-attention, and
#     Variational Quantum Circuits (VQC). Employs skip connections to merge
#     classical and quantum logic for highly stable gradient flows.
#     """
#     def __init__(
#         self,
#         config: ModelConfig,
#         clf_hidden_dims: Optional[List[int]] = None,
#         dropout_rate: float = 0.3
#     ):
#         super().__init__()
#         self.config = config
#         logger.info("Initializing Advanced Hybrid Quantum-Classical Classifier...")
# 
#         # 1. Classical Backbone Feature Extractor
#         backbone = getattr(config, 'backbone_name', 'resnet50')
#         self.feature_extractor = ClassicalFeatureExtractor(
#             output_dim=config.n_qubits,
#             backbone_name=backbone
#         )
# 
#         # 2. Attention Bridge
#         self.attention_block = FeatureAttentionBlock(
#             embed_dim=config.n_qubits,
#             dropout=dropout_rate
#         )
# 
#         # 3. Quantum Circuit Layer
#         self.quantum_circuit = VariationalQuantumCircuit(config)
# 
#         # 4. Skip Connection Dimension Mapping
#         # We concatenate classical (attention) features and quantum features
#         combined_dim = config.n_qubits * 2
# 
#         # 5. Flexible Classification Head
#         self.classifier = FlexibleClassifierHead(
#             in_features=combined_dim,
#             num_classes=config.num_classes,
#             hidden_dims=clf_hidden_dims,
#             dropout=dropout_rate
#         )
# 
#     def forward(self, x: torch.Tensor) -> torch.Tensor:
#         """
#         Forward Pass:
#         Image -> CNN -> Attention Bridge -> VQC -> Skip Connection Concat -> Classifier
#         """
#         # Feature Extraction
#         x_c = self.feature_extractor(x)
# 
#         # Attention Mechanism (includes intrinsic residual loops)
#         x_attn = self.attention_block(x_c)
# 
#         # Quantum Processing
#         x_q = self.quantum_circuit(x_attn)
# 
#         # Skip Connection: Bypass the quantum layer with classical attention features
#         # This allows the classifier to optimally weight classical vs. quantum embeddings
#         x_skip = torch.cat([x_attn, x_q], dim=1)
# 
#         # Final Prediction
#         out = self.classifier(x_skip)
# 
#         return out

"""Training Model"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile training/trainer.py
# import os
# import time
# from pathlib import Path
# from typing import Any, Dict, List, Optional, Tuple
# 
# import matplotlib.pyplot as plt
# import numpy as np
# import seaborn as sns
# import torch
# import torch.nn as nn
# import torch.optim as optim
# from sklearn.metrics import (
#     confusion_matrix,
#     f1_score,
#     precision_score,
#     recall_score,
#     roc_curve,
#     auc,
#     precision_recall_curve,
#     average_precision_score
# )
# from sklearn.preprocessing import label_binarize
# from torch.utils.tensorboard import SummaryWriter
# from torch.utils.data import DataLoader
# from tqdm import tqdm
# 
# from config.settings import ModelConfig
# from utils.logger import get_logger
# 
# logger = get_logger(__name__)
# 
# class EarlyStopping:
#     """Tracks validation loss and triggers early stopping to prevent overfitting."""
#     def __init__(self, patience: int = 5, min_delta: float = 0.0):
#         self.patience = patience
#         self.min_delta = min_delta
#         self.counter = 0
#         self.best_loss = None
#         self.early_stop = False
# 
#     def __call__(self, val_loss: float) -> bool:
#         if self.best_loss is None:
#             self.best_loss = val_loss
#         elif val_loss > self.best_loss - self.min_delta:
#             self.counter += 1
#             if self.counter >= self.patience:
#                 self.early_stop = True
#         else:
#             self.best_loss = val_loss
#             self.counter = 0
#         return self.early_stop
# 
# 
# class HybridModelTrainer:
#     """
#     Production-grade trainer with Automatic Mixed Precision (AMP), gradient clipping,
#     advanced scheduling, early stopping, TensorBoard logging, and evaluation graphing.
#     """
#     def __init__(self, model: nn.Module, config: ModelConfig, class_names: List[str] = ['Rain', 'Road', 'Sky']):
#         self.config = config
#         self.class_names = class_names
# 
#         # Automatic GPU support
#         self.device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
#         self.model = model.to(self.device)
#         logger.info(f"Trainer initialized. Target Device: {self.device}")
# 
#         # Optimization configuration
#         self.criterion = nn.CrossEntropyLoss()
#         self.optimizer = optim.AdamW(self.model.parameters(), lr=self.config.learning_rate, weight_decay=1e-4)
# 
#         # Cosine Annealing Learning Rate Scheduler
#         self.scheduler = optim.lr_scheduler.CosineAnnealingLR(
#             self.optimizer, T_max=self.config.epochs, eta_min=1e-6
#         )
# 
#         # Automatic Mixed Precision (AMP)
#         self.scaler = torch.amp.GradScaler('cuda' if torch.cuda.is_available() else 'cpu')
# 
#         # Tracking and Checkpointing
#         self.early_stopping = EarlyStopping(patience=7, min_delta=1e-4)
#         self.checkpoint_dir = Path(self.config.checkpoint_dir)
#         self.checkpoint_dir.mkdir(parents=True, exist_ok=True)
#         self.best_model_path = self.checkpoint_dir / "best_model.pt"
# 
#         # TensorBoard setup
#         self.tb_dir = Path("./assets/tensorboard_logs")
#         self.tb_dir.mkdir(parents=True, exist_ok=True)
#         self.writer = SummaryWriter(log_dir=str(self.tb_dir))
# 
#         self.start_epoch = 0
# 
#     def resume_from_checkpoint(self, path: str) -> None:
#         """Resumes training from a saved checkpoint."""
#         if not os.path.isfile(path):
#             logger.warning(f"No checkpoint found at {path}. Starting from scratch.")
#             return
# 
#         logger.info(f"Loading checkpoint from {path}")
#         checkpoint = torch.load(path, map_location=self.device)
# 
#         self.model.load_state_dict(checkpoint['model_state_dict'])
#         self.optimizer.load_state_dict(checkpoint['optimizer_state_dict'])
#         self.scheduler.load_state_dict(checkpoint['scheduler_state_dict'])
#         self.start_epoch = checkpoint['epoch'] + 1
# 
#         if 'scaler_state_dict' in checkpoint:
#             self.scaler.load_state_dict(checkpoint['scaler_state_dict'])
# 
#         logger.info(f"Successfully resumed from epoch {self.start_epoch}")
# 
#     def _save_checkpoint(self, epoch: int, val_loss: float, is_best: bool = False) -> None:
#         """Saves model state, optimizer, scheduler, and AMP scaler."""
#         state = {
#             'epoch': epoch,
#             'model_state_dict': self.model.state_dict(),
#             'optimizer_state_dict': self.optimizer.state_dict(),
#             'scheduler_state_dict': self.scheduler.state_dict(),
#             'scaler_state_dict': self.scaler.state_dict(),
#             'val_loss': val_loss
#         }
# 
#         # Save regular epoch checkpoint
#         checkpoint_path = self.checkpoint_dir / f"checkpoint_epoch_{epoch}.pt"
#         torch.save(state, checkpoint_path)
# 
#         # Overwrite best model if improved
#         if is_best:
#             torch.save(state, self.best_model_path)
#             logger.info(f"New best model saved with Val Loss: {val_loss:.4f}")
# 
#     def train_epoch(self, dataloader: DataLoader, epoch: int) -> Tuple[float, float]:
#         self.model.train()
#         running_loss = 0.0
#         correct, total = 0, 0
# 
#         pbar = tqdm(dataloader, desc=f"Epoch {epoch}/{self.config.epochs} [Train]")
#         for inputs, targets in pbar:
#             inputs, targets = inputs.to(self.device), targets.to(self.device)
# 
#             self.optimizer.zero_grad(set_to_none=True)
# 
#             # AMP Forward Pass
#             with torch.amp.autocast('cuda' if torch.cuda.is_available() else 'cpu'):
#                 outputs = self.model(inputs)
#                 loss = self.criterion(outputs, targets)
# 
#             # AMP Backward Pass & Optimization
#             self.scaler.scale(loss).backward()
# 
#             # Gradient Clipping (Unscale first)
#             self.scaler.unscale_(self.optimizer)
#             torch.nn.utils.clip_grad_norm_(self.model.parameters(), max_norm=1.0)
# 
#             self.scaler.step(self.optimizer)
#             self.scaler.update()
# 
#             running_loss += loss.item() * inputs.size(0)
#             _, predicted = outputs.max(1)
#             total += targets.size(0)
#             correct += predicted.eq(targets).sum().item()
# 
#             pbar.set_postfix({'loss': loss.item(), 'acc': correct/total})
# 
#         epoch_loss = running_loss / total
#         epoch_acc = correct / total
#         return epoch_loss, epoch_acc
# 
#     @torch.no_grad()
#     def validate_epoch(self, dataloader: DataLoader, epoch: int) -> Tuple[float, float, List[int], List[int], np.ndarray]:
#         self.model.eval()
#         running_loss = 0.0
#         correct, total = 0, 0
# 
#         all_targets = []
#         all_preds = []
#         all_probs = []
# 
#         pbar = tqdm(dataloader, desc=f"Epoch {epoch}/{self.config.epochs} [Val]")
#         for inputs, targets in pbar:
#             inputs, targets = inputs.to(self.device), targets.to(self.device)
# 
#             with torch.amp.autocast('cuda' if torch.cuda.is_available() else 'cpu'):
#                 outputs = self.model(inputs)
#                 loss = self.criterion(outputs, targets)
#                 probs = torch.softmax(outputs, dim=1)
# 
#             running_loss += loss.item() * inputs.size(0)
#             _, predicted = outputs.max(1)
#             total += targets.size(0)
#             correct += predicted.eq(targets).sum().item()
# 
#             all_targets.extend(targets.cpu().numpy())
#             all_preds.extend(predicted.cpu().numpy())
#             all_probs.append(probs.cpu().numpy())
# 
#             pbar.set_postfix({'loss': loss.item(), 'acc': correct/total})
# 
#         epoch_loss = running_loss / total
#         epoch_acc = correct / total
# 
#         return epoch_loss, epoch_acc, all_targets, all_preds, np.vstack(all_probs)
# 
#     def train(self, train_loader: DataLoader, val_loader: DataLoader) -> None:
#         """Main training loop with epoch timing, logging, and evaluation triggers."""
#         logger.info(f"Starting Training: {self.config.epochs} Epochs")
# 
#         for epoch in range(self.start_epoch, self.config.epochs + 1):
#             if epoch == 0: continue # Adjust if 1-indexed
#             start_time = time.time()
# 
#             # Train & Validate
#             train_loss, train_acc = self.train_epoch(train_loader, epoch)
#             val_loss, val_acc, val_targets, val_preds, val_probs = self.validate_epoch(val_loader, epoch)
# 
#             # LR Scheduler Step
#             self.scheduler.step()
#             current_lr = self.scheduler.get_last_lr()[0]
# 
#             # Log metrics to TensorBoard
#             self.writer.add_scalar('Loss/Train', train_loss, epoch)
#             self.writer.add_scalar('Loss/Validation', val_loss, epoch)
#             self.writer.add_scalar('Accuracy/Train', train_acc, epoch)
#             self.writer.add_scalar('Accuracy/Validation', val_acc, epoch)
#             self.writer.add_scalar('Learning_Rate', current_lr, epoch)
# 
#             time_taken = time.time() - start_time
#             logger.info(
#                 f"Epoch {epoch:03d} | Train Loss: {train_loss:.4f} | Val Loss: {val_loss:.4f} | "
#                 f"Train Acc: {train_acc:.4f} | Val Acc: {val_acc:.4f} | LR: {current_lr:.2e} | {time_taken:.1f}s"
#             )
# 
#             # Save Checkpoint & Check Best Model
#             is_best = val_loss < (self.early_stopping.best_loss or float('inf'))
#             self._save_checkpoint(epoch, val_loss, is_best)
# 
#             # Evaluate advanced metrics on best epoch
#             if is_best:
#                 self.evaluate_and_plot(val_targets, val_preds, val_probs, prefix=f"epoch_{epoch}")
# 
#             # Early Stopping Check
#             if self.early_stopping(val_loss):
#                 logger.info(f"Early stopping triggered at epoch {epoch}.")
#                 break
# 
#         self.writer.close()
#         logger.info(f"Training Complete. Best Model saved at: {self.best_model_path}")
# 
#     def evaluate_and_plot(self, y_true: List[int], y_pred: List[int], y_prob: np.ndarray, prefix: str = "final") -> None:
#         """Computes Precision, Recall, F1 and plots CM, ROC, and PR Curves."""
#         out_dir = Path("./visualization")
#         out_dir.mkdir(parents=True, exist_ok=True)
# 
#         # 1. Metrics Calculation
#         precision = precision_score(y_true, y_pred, average='weighted', zero_division=0)
#         recall = recall_score(y_true, y_pred, average='weighted', zero_division=0)
#         f1 = f1_score(y_true, y_pred, average='weighted', zero_division=0)
#         logger.info(f"--- Evaluation [{prefix}] ---")
#         logger.info(f"Precision: {precision:.4f} | Recall: {recall:.4f} | F1-Score: {f1:.4f}")
# 
#         # 2. Confusion Matrix Plot
#         cm = confusion_matrix(y_true, y_pred)
#         plt.figure(figsize=(8, 6))
#         sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', xticklabels=self.class_names, yticklabels=self.class_names)
#         plt.xlabel('Predicted Label')
#         plt.ylabel('True Label')
#         plt.title('Confusion Matrix')
#         plt.tight_layout()
#         plt.savefig(out_dir / f"confusion_matrix_{prefix}.png", dpi=300)
#         plt.close()
# 
#         # Label Binarization for Multiclass ROC & PR curves
#         y_true_bin = label_binarize(y_true, classes=[i for i in range(len(self.class_names))])
#         if y_true_bin.shape[1] == 1:
#             y_true_bin = np.hstack([1 - y_true_bin, y_true_bin])
# 
#         # 3. ROC Curve
#         plt.figure(figsize=(8, 6))
#         for i, class_name in enumerate(self.class_names):
#             fpr, tpr, _ = roc_curve(y_true_bin[:, i], y_prob[:, i])
#             roc_auc = auc(fpr, tpr)
#             plt.plot(fpr, tpr, lw=2, label=f'{class_name} (AUC = {roc_auc:.2f})')
# 
#         plt.plot([0, 1], [0, 1], color='gray', linestyle='--')
#         plt.xlim([0.0, 1.0])
#         plt.ylim([0.0, 1.05])
#         plt.xlabel('False Positive Rate')
#         plt.ylabel('True Positive Rate')
#         plt.title('Receiver Operating Characteristic (ROC)')
#         plt.legend(loc="lower right")
#         plt.grid(alpha=0.3)
#         plt.tight_layout()
#         plt.savefig(out_dir / f"roc_curve_{prefix}.png", dpi=300)
#         plt.close()
# 
#         # 4. Precision-Recall Curve
#         plt.figure(figsize=(8, 6))
#         for i, class_name in enumerate(self.class_names):
#             pr, re, _ = precision_recall_curve(y_true_bin[:, i], y_prob[:, i])
#             ap = average_precision_score(y_true_bin[:, i], y_prob[:, i])
#             plt.plot(re, pr, lw=2, label=f'{class_name} (AP = {ap:.2f})')
# 
#         plt.xlabel('Recall')
#         plt.ylabel('Precision')
#         plt.title('Precision-Recall Curve')
#         plt.legend(loc="lower left")
#         plt.grid(alpha=0.3)
#         plt.tight_layout()
#         plt.savefig(out_dir / f"pr_curve_{prefix}.png", dpi=300)
#         plt.close()

"""Camera"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile deployment/camera.py
# import threading
# import time
# from typing import Optional, Tuple
# 
# import cv2
# import numpy as np
# 
# from utils.logger import get_logger
# 
# logger = get_logger(__name__)
# 
# class ThreadedWebcam:
#     """
#     Thread-safe implementation of OpenCV webcam capture.
#     Runs I/O operations in a background thread to prevent UI blocking
#     and maintain high FPS.
#     """
#     def __init__(self, src: int = 0):
#         self.src = src
#         self.stream = cv2.VideoCapture(self.src)
#         self.stream.set(cv2.CAP_PROP_FRAME_WIDTH, 640)
#         self.stream.set(cv2.CAP_PROP_FRAME_HEIGHT, 480)
# 
#         if not self.stream.isOpened():
#             logger.error(f"Failed to open webcam source {self.src}")
#             raise RuntimeError(f"Webcam {self.src} not accessible.")
# 
#         self.grabbed, self.frame = self.stream.read()
#         self.stopped = False
#         self.lock = threading.Lock()
# 
#         # Start the background thread
#         self.thread = threading.Thread(target=self._update, args=(), daemon=True)
#         self.thread.start()
#         logger.info("ThreadedWebcam initialized and running.")
# 
#     def _update(self) -> None:
#         """Continuously pulls frames from the camera."""
#         while not self.stopped:
#             grabbed, frame = self.stream.read()
#             with self.lock:
#                 self.grabbed = grabbed
#                 self.frame = frame
#             # Tiny sleep to prevent high CPU usage in the thread
#             time.sleep(0.01)
# 
#     def read(self) -> Tuple[bool, Optional[np.ndarray]]:
#         """Returns the most recent frame."""
#         with self.lock:
#             if not self.grabbed or self.frame is None:
#                 return False, None
#             return True, self.frame.copy()
# 
#     def stop(self) -> None:
#         """Safely terminates the background thread and releases hardware."""
#         self.stopped = True
#         if self.thread.is_alive():
#             self.thread.join()
#         self.stream.release()
#         logger.info("ThreadedWebcam stopped and hardware released.")

"""Evaluation"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile evaluation/evaluation.py
# import time
# from pathlib import Path
# from typing import Dict, List, Tuple
# 
# import matplotlib.pyplot as plt
# import numpy as np
# import psutil
# import seaborn as sns
# import torch
# import torch.nn as nn
# from sklearn.metrics import (
#     accuracy_score,
#     auc,
#     confusion_matrix,
#     precision_score,
#     recall_score,
#     roc_curve,
# )
# from sklearn.preprocessing import label_binarize
# from torch.utils.data import DataLoader
# from tqdm import tqdm
# 
# from config.settings import ModelConfig
# from utils.logger import get_logger
# 
# logger = get_logger(__name__)
# 
# class HybridModelEvaluator:
#     """
#     Comprehensive evaluation suite for the Hybrid Quantum-Classical Classifier.
#     Computes rigorous statistical metrics, hardware performance profiles,
#     and detailed execution latencies for classical vs. quantum layers.
#     """
# 
#     def __init__(self, model: nn.Module, config: ModelConfig, class_names: List[str] = ['Rain', 'Road', 'Sky']):
#         self.config = config
#         self.class_names = class_names
#         self.device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
#         self.model = model.to(self.device)
#         self.model.eval()
# 
#         self.output_dir = Path("./visualization")
#         self.output_dir.mkdir(parents=True, exist_ok=True)
# 
#         logger.info(f"Evaluator initialized on device: {self.device}")
# 
#     @torch.no_grad()
#     def evaluate_dataset(self, dataloader: DataLoader) -> Tuple[List[int], List[int], np.ndarray, float]:
#         """Runs inference over the entire dataset to collect predictions and probabilities."""
#         all_targets = []
#         all_preds = []
#         all_probs = []
# 
#         start_time = time.perf_counter()
# 
#         for inputs, targets in tqdm(dataloader, desc="Evaluating Dataset"):
#             inputs = inputs.to(self.device)
# 
#             with torch.amp.autocast('cuda' if self.device.type == 'cuda' else 'cpu'):
#                 outputs = self.model(inputs)
#                 probs = torch.softmax(outputs, dim=1)
# 
#             _, predicted = outputs.max(1)
# 
#             all_targets.extend(targets.cpu().numpy())
#             all_preds.extend(predicted.cpu().numpy())
#             all_probs.append(probs.cpu().numpy())
# 
#         total_time = time.perf_counter() - start_time
# 
#         return all_targets, all_preds, np.vstack(all_probs), total_time
# 
#     def compute_classification_metrics(self, y_true: List[int], y_pred: List[int], y_prob: np.ndarray) -> Dict[str, float]:
#         """Calculates Accuracy, Precision, Recall, Sensitivity, and Specificity."""
#         cm = confusion_matrix(y_true, y_pred)
# 
#         # Calculate per-class metrics
#         specificities = []
#         sensitivities = []
# 
#         for i in range(len(self.class_names)):
#             tp = cm[i, i]
#             fp = cm[:, i].sum() - tp
#             fn = cm[i, :].sum() - tp
#             tn = cm.sum() - (tp + fp + fn)
# 
#             # Sensitivity is mathematically identical to Recall for that class
#             sensitivity = tp / (tp + fn) if (tp + fn) > 0 else 0.0
#             specificity = tn / (tn + fp) if (tn + fp) > 0 else 0.0
# 
#             sensitivities.append(sensitivity)
#             specificities.append(specificity)
# 
#         metrics = {
#             "Accuracy": accuracy_score(y_true, y_pred),
#             "Precision (Macro)": precision_score(y_true, y_pred, average='macro', zero_division=0),
#             "Recall/Sensitivity (Macro)": recall_score(y_true, y_pred, average='macro', zero_division=0),
#             "Specificity (Macro)": float(np.mean(specificities)),
#         }
# 
#         logger.info("--- Statistical Metrics ---")
#         for k, v in metrics.items():
#             logger.info(f"{k}: {v:.4f}")
# 
#         return metrics
# 
#     def profile_hardware(self, input_shape: Tuple[int, ...] = (1, 3, 64, 64), iterations: int = 50) -> Dict[str, float]:
#         """Profiles parameter count, memory usage, and layer-specific execution times."""
#         dummy_input = torch.randn(input_shape, device=self.device)
# 
#         # 1. Parameter Count
#         total_params = sum(p.numel() for p in self.model.parameters())
#         trainable_params = sum(p.numel() for p in self.model.parameters() if p.requires_grad)
# 
#         # 2. Memory Usage
#         if self.device.type == 'cuda':
#             memory_used = torch.cuda.memory_allocated() / (1024 ** 2) # MB
#         else:
#             memory_used = psutil.Process().memory_info().rss / (1024 ** 2) # MB
# 
#         # 3. Layer Timing Breakdown
#         classical_times = []
#         quantum_times = []
# 
#         # Warmup
#         for _ in range(10):
#             _ = self.model(dummy_input)
# 
#         # Precise Timing Loop
#         with torch.no_grad():
#             for _ in range(iterations):
#                 # Classical Phase 1: Feature Extraction & Attention
#                 torch.cuda.synchronize() if self.device.type == 'cuda' else None
#                 t0 = time.perf_counter()
# 
#                 x_c = self.model.feature_extractor(dummy_input)
#                 x_attn = self.model.attention_block(x_c)
# 
#                 torch.cuda.synchronize() if self.device.type == 'cuda' else None
#                 t1 = time.perf_counter()
# 
#                 # Quantum Phase
#                 x_q = self.model.quantum_circuit(x_attn)
# 
#                 torch.cuda.synchronize() if self.device.type == 'cuda' else None
#                 t2 = time.perf_counter()
# 
#                 # Classical Phase 2: Classification
#                 x_skip = torch.cat([x_attn, x_q], dim=1)
#                 _ = self.model.classifier(x_skip)
# 
#                 torch.cuda.synchronize() if self.device.type == 'cuda' else None
#                 t3 = time.perf_counter()
# 
#                 classical_times.append((t1 - t0) + (t3 - t2))
#                 quantum_times.append(t2 - t1)
# 
#         avg_classical_time = float(np.mean(classical_times))
#         avg_quantum_time = float(np.mean(quantum_times))
#         total_inference_time = avg_classical_time + avg_quantum_time
#         fps = 1.0 / total_inference_time if total_inference_time > 0 else 0
# 
#         hardware_metrics = {
#             "Total Parameters": total_params,
#             "Trainable Parameters": trainable_params,
#             "Memory Usage (MB)": memory_used,
#             "Classical Layer Time (s)": avg_classical_time,
#             "Quantum Layer Time (s)": avg_quantum_time,
#             "Total Inference Time (s)": total_inference_time,
#             "FPS": fps
#         }
# 
#         logger.info("--- Hardware & Performance Profile ---")
#         for k, v in hardware_metrics.items():
#             if isinstance(v, float):
#                 logger.info(f"{k}: {v:.6f}")
#             else:
#                 logger.info(f"{k}: {v:,}")
# 
#         return hardware_metrics
# 
#     def plot_confusion_matrix(self, y_true: List[int], y_pred: List[int]) -> None:
#         """Generates and saves a high-quality Confusion Matrix."""
#         cm = confusion_matrix(y_true, y_pred)
#         plt.figure(figsize=(8, 6))
#         sns.heatmap(
#             cm, annot=True, fmt='d', cmap='magma',
#             xticklabels=self.class_names, yticklabels=self.class_names
#         )
#         plt.xlabel('Predicted Label')
#         plt.ylabel('True Label')
#         plt.title('Hybrid Model Confusion Matrix')
#         plt.tight_layout()
#         plt.savefig(self.output_dir / "evaluation_confusion_matrix.png", dpi=300)
#         plt.close()
#         logger.info(f"Saved Confusion Matrix to {self.output_dir}")
# 
#     def plot_roc_curve(self, y_true: List[int], y_prob: np.ndarray) -> None:
#         """Generates and saves the Receiver Operating Characteristic (ROC) curves."""
#         # Binarize labels for multi-class ROC
#         y_true_bin = label_binarize(y_true, classes=[i for i in range(len(self.class_names))])
# 
#         # Handle edge case where there are only 2 classes
#         if y_true_bin.shape[1] == 1:
#             y_true_bin = np.hstack([1 - y_true_bin, y_true_bin])
# 
#         plt.figure(figsize=(10, 8))
# 
#         for i, class_name in enumerate(self.class_names):
#             fpr, tpr, _ = roc_curve(y_true_bin[:, i], y_prob[:, i])
#             roc_auc = auc(fpr, tpr)
#             plt.plot(fpr, tpr, lw=2, label=f'{class_name} (AUC = {roc_auc:.3f})')
# 
#         plt.plot([0, 1], [0, 1], color='gray', linestyle='--', lw=2)
#         plt.xlim([0.0, 1.0])
#         plt.ylim([0.0, 1.05])
#         plt.xlabel('False Positive Rate (1 - Specificity)')
#         plt.ylabel('True Positive Rate (Sensitivity)')
#         plt.title('Multi-Class ROC Curve (Quantum-Classical Classifier)')
#         plt.legend(loc="lower right")
#         plt.grid(alpha=0.3)
#         plt.tight_layout()
#         plt.savefig(self.output_dir / "evaluation_roc_curve.png", dpi=300)
#         plt.close()
#         logger.info(f"Saved ROC Curves to {self.output_dir}")
# 
#     def run_full_evaluation(self, test_loader: DataLoader) -> Dict[str, float]:
#         """Executes the complete evaluation pipeline."""
#         logger.info("Starting Full Model Evaluation...")
# 
#         # 1. Dataset Inference
#         y_true, y_pred, y_prob, dataset_time = self.evaluate_dataset(test_loader)
# 
#         # 2. Compute Metrics
#         stats = self.compute_classification_metrics(y_true, y_pred, y_prob)
# 
#         # 3. Hardware Profiling
#         hardware_stats = self.profile_hardware(
#             input_shape=(1, 3, self.config.image_size[0], self.config.image_size[1])
#         )
# 
#         # 4. Visualizations
#         self.plot_confusion_matrix(y_true, y_pred)
#         self.plot_roc_curve(y_true, y_prob)
# 
#         # Merge dictionaries for final return
#         return {**stats, **hardware_stats}

"""Dashboard"""

