# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CpecvWxkSlf9vUBZZh2ab9ybXY-ewP7z
"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# from flask import Flask, render_template, request, jsonify
# from quantum_core import QuantumNode, QuantumChannel, QKDPipeline, EavesdropDetector
# import random
# import logging
# 
# # Disable default Flask logging to keep Colab clean
# log = logging.getLogger('werkzeug')
# log.setLevel(logging.ERROR)
# 
# app = Flask(__name__)
# 
# @app.route('/')
# def index():
#     return render_template('index.html')
# 
# @app.route('/api/simulate', methods=['GET'])
# def simulate():
#     # Parse inputs
#     sim_bits = int(request.args.get('bits', 1024))
#     noise_level = float(request.args.get('noise', 0.015))
#     attack_active = request.args.get('attack', 'false') == 'true'
# 
#     # 1. Initialize Network
#     alice = QuantumNode("Alice")
#     channel = QuantumChannel(eve_present=attack_active, noise_level=noise_level)
# 
#     # 2. Transmit
#     alice_bits, alice_bases = alice.generate_raw_data(sim_bits)
#     bob_bits = channel.transmit(alice_bits, alice_bases)
#     bob_bases = [random.choice(['+', 'x']) for _ in range(sim_bits)]
# 
#     # 3. Sift
#     alice_sifted, bob_sifted = QKDPipeline.sift_keys(alice_bases, bob_bases, alice_bits, bob_bits)
# 
#     # 4. Detect
#     qber, final_alice, final_bob = EavesdropDetector.estimate_parameter(alice_sifted, bob_sifted)
#     is_secure = qber < 11.0
# 
#     # 5. Result Packing
#     final_hash = ""
#     if is_secure:
#         final_hash = QKDPipeline.amplify_privacy(final_alice)
# 
#     return jsonify({
#         "metrics": {
#             "sifted_key_length": len(alice_sifted),
#             "qber_percentage": round(qber, 2),
#             "is_secure": is_secure
#         },
#         "final_key_hash": final_hash
#     })
# 
# if __name__ == '__main__':
#     app.run(host='0.0.0.0', port=5000)