# -*- coding: utf-8 -*-
"""Quantum_core

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CpecvWxkSlf9vUBZZh2ab9ybXY-ewP7z
"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile quantum_core.py
# import random
# import hashlib
# 
# class QuantumNode:
#     def __init__(self, name):
#         self.name = name
# 
#     def generate_raw_data(self, num_bits):
#         bits = [random.randint(0, 1) for _ in range(num_bits)]
#         bases = [random.choice(['+', 'x']) for _ in range(num_bits)]
#         return bits, bases
# 
# class QuantumChannel:
#     def __init__(self, eve_present=False, eavesdrop_rate=1.0, noise_level=0.015):
#         self.eve_present = eve_present
#         self.eavesdrop_rate = eavesdrop_rate
#         self.noise_level = noise_level
# 
#     def transmit(self, alice_bits, alice_bases):
#         bob_received_bits = []
#         for bit, base in zip(alice_bits, alice_bases):
#             current_bit = bit
#             current_base = base
# 
#             if random.random() < self.noise_level:
#                 current_bit = 1 - current_bit
# 
#             if self.eve_present and random.random() < self.eavesdrop_rate:
#                 eve_basis = random.choice(['+', 'x'])
#                 if eve_basis != current_base:
#                     current_bit = random.randint(0, 1)
#             bob_received_bits.append(current_bit)
#         return bob_received_bits
# 
# class QKDPipeline:
#     @staticmethod
#     def sift_keys(alice_bases, bob_bases, alice_bits, bob_bits):
#         sifted_alice = []
#         sifted_bob = []
#         for i in range(len(alice_bases)):
#             if alice_bases[i] == bob_bases[i]:
#                 sifted_alice.append(alice_bits[i])
#                 sifted_bob.append(bob_bits[i])
#         return sifted_alice, sifted_bob
# 
#     @staticmethod
#     def amplify_privacy(bit_list):
#         bit_string = "".join(map(str, bit_list)).encode('utf-8')
#         return hashlib.sha256(bit_string).hexdigest()
# 
# class EavesdropDetector:
#     @staticmethod
#     def estimate_parameter(alice_sifted, bob_sifted, sample_size=0.25):
#         k = len(alice_sifted)
#         num_samples = int(k * sample_size)
#         if num_samples == 0: return 0.0, alice_sifted, bob_sifted
# 
#         sample_indices = random.sample(range(k), num_samples)
#         mismatches = sum(1 for idx in sample_indices if alice_sifted[idx] != bob_sifted[idx])
# 
#         qber = (mismatches / num_samples) * 100
#         remaining_alice = [alice_sifted[i] for i in range(k) if i not in sample_indices]
#         remaining_bob = [bob_sifted[i] for i in range(k) if i not in sample_indices]
#         return qber, remaining_alice, remaining_bob