# -*- coding: utf-8 -*-
"""Security Tool kit

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZRLF5LV6xB7Lo6NDsC9dg5nOT6IfeuzZ
"""

import qiskit
import numpy
import matplotlib
import cryptography

print("✅ Qiskit Version      :", qiskit.__version__)
print("✅ NumPy Version       :", numpy.__version__)
print("✅ Matplotlib Version  :", matplotlib.__version__)
print("✅ Cryptography Version:", cryptography.__version__)

print("\n All required libraries are installed successfully!")

from qiskit import QuantumCircuit

# Create a simple quantum circuit
qc = QuantumCircuit(1)
qc.h(0)

print("Quantum Circuit:\n")
print(qc)

# Create directories for Flask templates and static assets
!mkdir -p templates static

import random
import hashlib

class QuantumNode:
    def __init__(self, name):
        self.name = name

    def generate_raw_data(self, num_bits):
        bits = [random.randint(0, 1) for _ in range(num_bits)]
        bases = [random.choice(['+', 'x']) for _ in range(num_bits)]
        return bits, bases

class QuantumChannel:
    def __init__(self, eve_present=False, eavesdrop_rate=1.0, noise_level=0.015):
        self.eve_present = eve_present
        self.eavesdrop_rate = eavesdrop_rate
        self.noise_level = noise_level

    def transmit(self, alice_bits, alice_bases):
        bob_received_bits = []
        for bit, base in zip(alice_bits, alice_bases):
            current_bit = bit
            current_base = base

            if random.random() < self.noise_level:
                current_bit = 1 - current_bit

            if self.eve_present and random.random() < self.eavesdrop_rate:
                eve_basis = random.choice(['+', 'x'])
                if eve_basis != current_base:
                    current_bit = random.randint(0, 1)
            bob_received_bits.append(current_bit)
        return bob_received_bits

class QKDPipeline:
    @staticmethod
    def sift_keys(alice_bases, bob_bases, alice_bits, bob_bits):
        sifted_alice = []
        sifted_bob = []
        for i in range(len(alice_bases)):
            if alice_bases[i] == bob_bases[i]:
                sifted_alice.append(alice_bits[i])
                sifted_bob.append(bob_bits[i])
        return sifted_alice, sifted_bob

    @staticmethod
    def amplify_privacy(bit_list):
        bit_string = "".join(map(str, bit_list)).encode('utf-8')
        return hashlib.sha256(bit_string).hexdigest()

class EavesdropDetector:
    @staticmethod
    def estimate_parameter(alice_sifted, bob_sifted, sample_size=0.25):
        k = len(alice_sifted)
        num_samples = int(k * sample_size)
        if num_samples == 0: return 0.0, alice_sifted, bob_sifted

        sample_indices = random.sample(range(k), num_samples)
        mismatches = sum(1 for idx in sample_indices if alice_sifted[idx] != bob_sifted[idx])

        qber = (mismatches / num_samples) * 100
        remaining_alice = [alice_sifted[i] for i in range(k) if i not in sample_indices]
        remaining_bob = [bob_sifted[i] for i in range(k) if i not in sample_indices]
        return qber, remaining_alice, remaining_bob

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Quantum Security Toolkit</title>
    <script src="https://cdn.tailwindcss.com"></script>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css" rel="stylesheet">
    <style>
        body { background-color: #0f172a; color: #e2e8f0; font-family: 'Inter', sans-serif; }
        .glass-panel { background: rgba(30, 41, 59, 0.7); backdrop-filter: blur(10px); border: 1px solid rgba(56, 189, 248, 0.2); }
        .neon-text { text-shadow: 0 0 10px rgba(56, 189, 248, 0.8); }
        .neon-shadow { box-shadow: 0 0 15px rgba(56, 189, 248, 0.4); }
        .btn-glow:hover { box-shadow: 0 0 20px rgba(56, 189, 248, 0.7); transform: translateY(-2px); }
        transition: all 0.3s ease;
    </style>
</head>
<body class="min-h-screen flex flex-col items-center p-6">

    <!-- Hero Section -->
    <header class="text-center mt-10 mb-12">
        <h1 class="text-5xl font-extrabold text-sky-400 neon-text mb-4"><i class="fa-solid fa-atom"></i> Quantum Security Toolkit</h1>
        <p class="text-lg text-slate-400 max-w-2xl mx-auto">Simulate the BB84 Quantum Key Distribution (QKD) protocol. Test channel security against eavesdropping attacks in real-time.</p>
    </header>

    <div class="w-full max-w-5xl grid grid-cols-1 lg:grid-cols-3 gap-8">

        <!-- Controls Panel -->
        <div class="glass-panel p-8 rounded-2xl col-span-1 h-fit">
            <h2 class="text-2xl font-bold text-sky-300 mb-6 border-b border-sky-900 pb-2"><i class="fa-solid fa-sliders"></i> Configuration</h2>
            <form id="qkd-form" class="space-y-6">
                <div>
                    <label class="block text-sm font-medium mb-2">Bits to Transmit (Photons)</label>
                    <input type="number" id="bits" value="1024" class="w-full bg-slate-800 border border-slate-600 rounded-lg p-3 text-white focus:outline-none focus:border-sky-400 focus:ring-1 focus:ring-sky-400">
                </div>
                <div>
                    <label class="block text-sm font-medium mb-2">Fiber Noise Level (%)</label>
                    <input type="number" step="0.01" id="noise" value="0.015" class="w-full bg-slate-800 border border-slate-600 rounded-lg p-3 text-white focus:outline-none focus:border-sky-400 focus:ring-1 focus:ring-sky-400">
                </div>
                <div class="flex items-center mt-4">
                    <input type="checkbox" id="attack" class="w-5 h-5 text-sky-500 bg-slate-800 border-slate-600 rounded focus:ring-sky-500">
                    <label for="attack" class="ml-3 text-md font-semibold text-rose-400">Enable Eve's Attack (Interception)</label>
                </div>
                <button type="submit" class="w-full bg-sky-500 hover:bg-sky-400 text-slate-900 font-bold py-3 px-4 rounded-lg btn-glow transition-all mt-6">
                    <i class="fa-solid fa-satellite-dish"></i> Execute Protocol
                </button>
            </form>
        </div>

        <!-- Dashboard Results -->
        <div class="col-span-1 lg:col-span-2 space-y-6">
            <!-- Status Card -->
            <div id="status-card" class="glass-panel p-8 rounded-2xl flex items-center justify-between opacity-50">
                <div>
                    <h3 class="text-lg text-slate-400 font-semibold uppercase tracking-wider">Security Status</h3>
                    <p id="status-text" class="text-3xl font-bold text-slate-500 mt-2">Awaiting Execution...</p>
                </div>
                <div id="status-icon" class="text-5xl text-slate-600">
                    <i class="fa-solid fa-shield-halved"></i>
                </div>
            </div>

            <!-- Metrics Grid -->
            <div class="grid grid-cols-2 gap-6">
                <div class="glass-panel p-6 rounded-2xl text-center">
                    <h4 class="text-slate-400 font-medium mb-2">Sifted Key Length</h4>
                    <p id="sifted-len" class="text-4xl font-black text-sky-300">0</p>
                    <p class="text-xs text-slate-500 mt-2">Usable bits after basis matching</p>
                </div>
                <div class="glass-panel p-6 rounded-2xl text-center">
                    <h4 class="text-slate-400 font-medium mb-2">Quantum Bit Error Rate</h4>
                    <p id="qber-val" class="text-4xl font-black text-sky-300">0.00%</p>
                    <p class="text-xs text-slate-500 mt-2">Safety Threshold: 11.0%</p>
                </div>
            </div>

            <!-- Derived Key Hash -->
            <div class="glass-panel p-6 rounded-2xl">
                <h4 class="text-slate-400 font-medium mb-2"><i class="fa-solid fa-key"></i> Final AES-256 Derived Key (Privacy Amplified)</h4>
                <div class="bg-slate-900 p-4 rounded border border-slate-700 font-mono text-sm break-all text-emerald-400" id="final-key">
                    Waiting for secure key generation...
                </div>
            </div>
        </div>
    </div>

    <script>
        document.getElementById('qkd-form').addEventListener('submit', async (e) => {
            e.preventDefault();

            // Visual loading state
            document.getElementById('status-text').innerText = "Transmitting Qubits...";
            document.getElementById('status-card').className = "glass-panel p-8 rounded-2xl flex items-center justify-between opacity-100 neon-shadow animate-pulse";

            const bits = document.getElementById('bits').value;
            const noise = document.getElementById('noise').value;
            const attack = document.getElementById('attack').checked;

            try {
                const response = await fetch(`/api/simulate?bits=${bits}&noise=${noise}&attack=${attack}`);
                const data = await response.json();

                // Update Metrics
                document.getElementById('sifted-len').innerText = data.metrics.sifted_key_length;
                document.getElementById('qber-val').innerText = data.metrics.qber_percentage + "%";

                const statusCard = document.getElementById('status-card');
                const statusText = document.getElementById('status-text');
                const statusIcon = document.getElementById('status-icon');
                const finalKey = document.getElementById('final-key');

                if (data.metrics.is_secure) {
                    statusCard.className = "glass-panel p-8 rounded-2xl flex items-center justify-between opacity-100 border-emerald-500";
                    statusCard.style.boxShadow = "0 0 20px rgba(16, 185, 129, 0.3)";
                    statusText.innerText = "SECURE CONNECTION";
                    statusText.className = "text-3xl font-bold text-emerald-400 mt-2";
                    statusIcon.innerHTML = '<i class="fa-solid fa-shield-check text-emerald-500"></i>';
                    finalKey.innerText = data.final_key_hash;
                    finalKey.className = "bg-slate-900 p-4 rounded border border-emerald-800 font-mono text-sm break-all text-emerald-400";
                } else {
                    statusCard.className = "glass-panel p-8 rounded-2xl flex items-center justify-between opacity-100 border-rose-500";
                    statusCard.style.boxShadow = "0 0 20px rgba(244, 63, 94, 0.3)";
                    statusText.innerText = "COMPROMISED (EVE DETECTED)";
                    statusText.className = "text-3xl font-bold text-rose-500 mt-2";
                    statusIcon.innerHTML = '<i class="fa-solid fa-user-secret text-rose-500"></i>';
                    finalKey.innerText = "ABORTED: Keys discarded to prevent data leakage.";
                    finalKey.className = "bg-slate-900 p-4 rounded border border-rose-800 font-mono text-sm break-all text-rose-400";
                }

            } catch (error) {
                alert("An error occurred during simulation.");
                console.error(error);
            }
        });
    </script>
</body>
</html>

from flask import Flask, render_template, request, jsonify
from quantum_core import QuantumNode, QuantumChannel, QKDPipeline, EavesdropDetector
import random
import logging

# Disable default Flask logging to keep Colab clean
log = logging.getLogger('werkzeug')
log.setLevel(logging.ERROR)

app = Flask(__name__)

@app.route('/')
def index():
    return render_template('index.html')

@app.route('/api/simulate', methods=['GET'])
def simulate():
    # Parse inputs
    sim_bits = int(request.args.get('bits', 1024))
    noise_level = float(request.args.get('noise', 0.015))
    attack_active = request.args.get('attack', 'false') == 'true'

    # 1. Initialize Network
    alice = QuantumNode("Alice")
    channel = QuantumChannel(eve_present=attack_active, noise_level=noise_level)

    # 2. Transmit
    alice_bits, alice_bases = alice.generate_raw_data(sim_bits)
    bob_bits = channel.transmit(alice_bits, alice_bases)
    bob_bases = [random.choice(['+', 'x']) for _ in range(sim_bits)]

    # 3. Sift
    alice_sifted, bob_sifted = QKDPipeline.sift_keys(alice_bases, bob_bases, alice_bits, bob_bits)

    # 4. Detect
    qber, final_alice, final_bob = EavesdropDetector.estimate_parameter(alice_sifted, bob_sifted)
    is_secure = qber < 11.0

    # 5. Result Packing
    final_hash = ""
    if is_secure:
        final_hash = QKDPipeline.amplify_privacy(final_alice)

    return jsonify({
        "metrics": {
            "sifted_key_length": len(alice_sifted),
            "qber_percentage": round(qber, 2),
            "is_secure": is_secure
        },
        "final_key_hash": final_hash
    })

if __name__ == '__main__':
    app.run(host='0.0.0.0', port=5000)

import threading
from google.colab.output import eval_js

# Start the Flask app in a background thread so it doesn't block the cell
def run_flask():
    !python app.py

thread = threading.Thread(target=run_flask)
thread.start()

# Generate the public link to access the local server
print("="*60)
print("🚀 YOUR QUANTUM SECURITY TOOLKIT IS RUNNING!")
print("Click the link below to open the Web Interface:")
print(eval_js("google.colab.kernel.proxyPort(5000)"))
print("="*60)