# -*- coding: utf-8 -*-
"""Set up

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZRLF5LV6xB7Lo6NDsC9dg5nOT6IfeuzZ
"""

# Install required Python libraries

!pip install -q qiskit
!pip install -q numpy
!pip install -q matplotlib
!pip install -q cryptography

# Verify installed package versions

import qiskit
import numpy
import matplotlib
import cryptography

print("✅ Qiskit Version      :", qiskit.__version__)
print("✅ NumPy Version       :", numpy.__version__)
print("✅ Matplotlib Version  :", matplotlib.__version__)
print("✅ Cryptography Version:", cryptography.__version__)

print("\n All required libraries are installed successfully!")

from qiskit import QuantumCircuit

# Create a simple quantum circuit
qc = QuantumCircuit(1)
qc.h(0)

print("Quantum Circuit:\n")
print(qc)