# -*- coding: utf-8 -*-
"""index.html

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CpecvWxkSlf9vUBZZh2ab9ybXY-ewP7z
"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile templates/index.html
# <!DOCTYPE html>
# <html lang="en">
# <head>
#     <meta charset="UTF-8">
#     <meta name="viewport" content="width=device-width, initial-scale=1.0">
#     <title>Quantum Security Toolkit</title>
#     <script src="https://cdn.tailwindcss.com"></script>
#     <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css" rel="stylesheet">
#     <style>
#         body { background-color: #0f172a; color: #e2e8f0; font-family: 'Inter', sans-serif; }
#         .glass-panel { background: rgba(30, 41, 59, 0.7); backdrop-filter: blur(10px); border: 1px solid rgba(56, 189, 248, 0.2); }
#         .neon-text { text-shadow: 0 0 10px rgba(56, 189, 248, 0.8); }
#         .neon-shadow { box-shadow: 0 0 15px rgba(56, 189, 248, 0.4); }
#         .btn-glow:hover { box-shadow: 0 0 20px rgba(56, 189, 248, 0.7); transform: translateY(-2px); }
#         transition: all 0.3s ease;
#     </style>
# </head>
# <body class="min-h-screen flex flex-col items-center p-6">
# 
#     <!-- Hero Section -->
#     <header class="text-center mt-10 mb-12">
#         <h1 class="text-5xl font-extrabold text-sky-400 neon-text mb-4"><i class="fa-solid fa-atom"></i> Quantum Security Toolkit</h1>
#         <p class="text-lg text-slate-400 max-w-2xl mx-auto">Simulate the BB84 Quantum Key Distribution (QKD) protocol. Test channel security against eavesdropping attacks in real-time.</p>
#     </header>
# 
#     <div class="w-full max-w-5xl grid grid-cols-1 lg:grid-cols-3 gap-8">
# 
#         <!-- Controls Panel -->
#         <div class="glass-panel p-8 rounded-2xl col-span-1 h-fit">
#             <h2 class="text-2xl font-bold text-sky-300 mb-6 border-b border-sky-900 pb-2"><i class="fa-solid fa-sliders"></i> Configuration</h2>
#             <form id="qkd-form" class="space-y-6">
#                 <div>
#                     <label class="block text-sm font-medium mb-2">Bits to Transmit (Photons)</label>
#                     <input type="number" id="bits" value="1024" class="w-full bg-slate-800 border border-slate-600 rounded-lg p-3 text-white focus:outline-none focus:border-sky-400 focus:ring-1 focus:ring-sky-400">
#                 </div>
#                 <div>
#                     <label class="block text-sm font-medium mb-2">Fiber Noise Level (%)</label>
#                     <input type="number" step="0.01" id="noise" value="0.015" class="w-full bg-slate-800 border border-slate-600 rounded-lg p-3 text-white focus:outline-none focus:border-sky-400 focus:ring-1 focus:ring-sky-400">
#                 </div>
#                 <div class="flex items-center mt-4">
#                     <input type="checkbox" id="attack" class="w-5 h-5 text-sky-500 bg-slate-800 border-slate-600 rounded focus:ring-sky-500">
#                     <label for="attack" class="ml-3 text-md font-semibold text-rose-400">Enable Eve's Attack (Interception)</label>
#                 </div>
#                 <button type="submit" class="w-full bg-sky-500 hover:bg-sky-400 text-slate-900 font-bold py-3 px-4 rounded-lg btn-glow transition-all mt-6">
#                     <i class="fa-solid fa-satellite-dish"></i> Execute Protocol
#                 </button>
#             </form>
#         </div>
# 
#         <!-- Dashboard Results -->
#         <div class="col-span-1 lg:col-span-2 space-y-6">
#             <!-- Status Card -->
#             <div id="status-card" class="glass-panel p-8 rounded-2xl flex items-center justify-between opacity-50">
#                 <div>
#                     <h3 class="text-lg text-slate-400 font-semibold uppercase tracking-wider">Security Status</h3>
#                     <p id="status-text" class="text-3xl font-bold text-slate-500 mt-2">Awaiting Execution...</p>
#                 </div>
#                 <div id="status-icon" class="text-5xl text-slate-600">
#                     <i class="fa-solid fa-shield-halved"></i>
#                 </div>
#             </div>
# 
#             <!-- Metrics Grid -->
#             <div class="grid grid-cols-2 gap-6">
#                 <div class="glass-panel p-6 rounded-2xl text-center">
#                     <h4 class="text-slate-400 font-medium mb-2">Sifted Key Length</h4>
#                     <p id="sifted-len" class="text-4xl font-black text-sky-300">0</p>
#                     <p class="text-xs text-slate-500 mt-2">Usable bits after basis matching</p>
#                 </div>
#                 <div class="glass-panel p-6 rounded-2xl text-center">
#                     <h4 class="text-slate-400 font-medium mb-2">Quantum Bit Error Rate</h4>
#                     <p id="qber-val" class="text-4xl font-black text-sky-300">0.00%</p>
#                     <p class="text-xs text-slate-500 mt-2">Safety Threshold: 11.0%</p>
#                 </div>
#             </div>
# 
#             <!-- Derived Key Hash -->
#             <div class="glass-panel p-6 rounded-2xl">
#                 <h4 class="text-slate-400 font-medium mb-2"><i class="fa-solid fa-key"></i> Final AES-256 Derived Key (Privacy Amplified)</h4>
#                 <div class="bg-slate-900 p-4 rounded border border-slate-700 font-mono text-sm break-all text-emerald-400" id="final-key">
#                     Waiting for secure key generation...
#                 </div>
#             </div>
#         </div>
#     </div>
# 
#     <script>
#         document.getElementById('qkd-form').addEventListener('submit', async (e) => {
#             e.preventDefault();
# 
#             // Visual loading state
#             document.getElementById('status-text').innerText = "Transmitting Qubits...";
#             document.getElementById('status-card').className = "glass-panel p-8 rounded-2xl flex items-center justify-between opacity-100 neon-shadow animate-pulse";
# 
#             const bits = document.getElementById('bits').value;
#             const noise = document.getElementById('noise').value;
#             const attack = document.getElementById('attack').checked;
# 
#             try {
#                 const response = await fetch(`/api/simulate?bits=${bits}&noise=${noise}&attack=${attack}`);
#                 const data = await response.json();
# 
#                 // Update Metrics
#                 document.getElementById('sifted-len').innerText = data.metrics.sifted_key_length;
#                 document.getElementById('qber-val').innerText = data.metrics.qber_percentage + "%";
# 
#                 const statusCard = document.getElementById('status-card');
#                 const statusText = document.getElementById('status-text');
#                 const statusIcon = document.getElementById('status-icon');
#                 const finalKey = document.getElementById('final-key');
# 
#                 if (data.metrics.is_secure) {
#                     statusCard.className = "glass-panel p-8 rounded-2xl flex items-center justify-between opacity-100 border-emerald-500";
#                     statusCard.style.boxShadow = "0 0 20px rgba(16, 185, 129, 0.3)";
#                     statusText.innerText = "SECURE CONNECTION";
#                     statusText.className = "text-3xl font-bold text-emerald-400 mt-2";
#                     statusIcon.innerHTML = '<i class="fa-solid fa-shield-check text-emerald-500"></i>';
#                     finalKey.innerText = data.final_key_hash;
#                     finalKey.className = "bg-slate-900 p-4 rounded border border-emerald-800 font-mono text-sm break-all text-emerald-400";
#                 } else {
#                     statusCard.className = "glass-panel p-8 rounded-2xl flex items-center justify-between opacity-100 border-rose-500";
#                     statusCard.style.boxShadow = "0 0 20px rgba(244, 63, 94, 0.3)";
#                     statusText.innerText = "COMPROMISED (EVE DETECTED)";
#                     statusText.className = "text-3xl font-bold text-rose-500 mt-2";
#                     statusIcon.innerHTML = '<i class="fa-solid fa-user-secret text-rose-500"></i>';
#                     finalKey.innerText = "ABORTED: Keys discarded to prevent data leakage.";
#                     finalKey.className = "bg-slate-900 p-4 rounded border border-rose-800 font-mono text-sm break-all text-rose-400";
#                 }
# 
#             } catch (error) {
#                 alert("An error occurred during simulation.");
#                 console.error(error);
#             }
#         });
#     </script>
# </body>
# </html>