# -*- coding: utf-8 -*-
"""web app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CpecvWxkSlf9vUBZZh2ab9ybXY-ewP7z
"""

import threading
from google.colab.output import eval_js

# Start the Flask app in a background thread so it doesn't block the cell
def run_flask():
    !python app.py

thread = threading.Thread(target=run_flask)
thread.start()

# Generate the public link to access the local server
print("="*60)
print("🚀 YOUR QUANTUM SECURITY TOOLKIT IS RUNNING!")
print("Click the link below to open the Web Interface:")
print(eval_js("google.colab.kernel.proxyPort(5000)"))
print("="*60)