# -*- coding: utf-8 -*-
"""Quantum Cryptography

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DE3SbrEMzUD76-SloSilgePltx0DKLde

# BB84 Quantum Communication Protocol
"""

pip -q install qiskit

from qiskit import QuantumCircuit
from qiskit.primitives import StatevectorSampler
import random

# Number of qubits
N = 8

# Alice Generates Random Bits

alice_bits = [random.randint(0, 1) for _ in range(N)]

# 0 = Z Basis (+)
# 1 = X Basis (×)
alice_bases = [random.randint(0, 1) for _ in range(N)]

# Bob randomly chooses bases
bob_bases = [random.randint(0, 1) for _ in range(N)]

print("="*60)
print("ALICE")
print("="*60)
print("Alice Bits : ", alice_bits)
print("Alice Bases:", alice_bases)

print("\nBOB")
print("="*60)
print("Bob Bases  :", bob_bases)


# Alice Encodes Qubits

circuits = []

for bit, basis in zip(alice_bits, alice_bases):

    qc = QuantumCircuit(1, 1)

    # Encode bit
    if bit == 1:
        qc.x(0)

    # Encode basis
    if basis == 1:
        qc.h(0)

    # Bob measurement basis
    if bob_bases[len(circuits)] == 1:
        qc.h(0)

    qc.measure(0, 0)

    circuits.append(qc)


# Execute

sampler = StatevectorSampler()

job = sampler.run(circuits, shots=1)

result = job.result()


# Bob Measurement Results

bob_bits = []

for pub_result in result:

    counts = pub_result.data.c.get_counts()

    measured = list(counts.keys())[0]

    bob_bits.append(int(measured))

print("\nBob Measured Bits:", bob_bits)

# Basis Comparison

print("\n")
print("="*60)
print("BASIS COMPARISON")
print("="*60)

shared_key_alice = []
shared_key_bob = []

for i in range(N):

    if alice_bases[i] == bob_bases[i]:

        shared_key_alice.append(alice_bits[i])
        shared_key_bob.append(bob_bits[i])

        print(f"Position {i+1} : Match ✓")

    else:

        print(f"Position {i+1} : Discard ✗")

print("\n")
print("="*60)
print("SHARED SECRET KEY")
print("="*60)

print("Alice Key:", shared_key_alice)
print("Bob Key  :", shared_key_bob)


# Check if Keys Match

if shared_key_alice == shared_key_bob:
    print("\nSecure Key Successfully Shared!")
else:
    print("\nErrors Detected in Shared Key!")


# QBER Calculation

errors = sum(a != b for a, b in zip(shared_key_alice, shared_key_bob))

if len(shared_key_alice) > 0:
    qber = errors / len(shared_key_alice)
else:
    qber = 0

print("\nQuantum Bit Error Rate (QBER):", round(qber, 3))

if qber > 0:
    print("Possible Eavesdropping or Noise Detected!")
else:
    print("Communication is Secure.")