# -*- coding: utf-8 -*-
"""App

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16n8xaz6j24OYC9IN_8OITwBlvqHwnIFb
"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import os
# import matplotlib
# matplotlib.use('Agg')
# 
# from flask import Flask, render_template, request
# from quantum.bell_states import run_bell_simulation
# from quantum.entanglement import run_entanglement_simulation
# from quantum.teleportation import run_teleportation_simulation
# 
# app = Flask(__name__)
# app.config['SECRET_KEY'] = 'quantum-secret-key'
# app.config['OUTPUT_DIR'] = os.path.join(app.root_path, 'static', 'outputs')
# 
# @app.route("/")
# def dashboard():
#     return render_template("dashboard.html", active_page='dashboard')
# 
# @app.route("/bell", methods=['GET', 'POST'])
# def bell_states():
#     basis = request.form.get('basis', 'Z') if request.method == 'POST' else 'Z'
#     counts, circuit_img, hist_img, correlation = run_bell_simulation(app.config['OUTPUT_DIR'], basis)
#     return render_template("bell.html", active_page='bell', counts=counts, circuit_img=circuit_img, hist_img=hist_img, correlation=correlation, current_basis=basis)
# 
# @app.route("/entanglement", methods=['GET', 'POST'])
# def entanglement():
#     basis = request.form.get('basis', 'Z') if request.method == 'POST' else 'Z'
#     counts, circuit_img, hist_img, correlation = run_entanglement_simulation(app.config['OUTPUT_DIR'], basis)
#     return render_template("entanglement.html", active_page='entanglement', counts=counts, circuit_img=circuit_img, hist_img=hist_img, correlation=correlation, current_basis=basis)
# 
# @app.route("/teleportation", methods=['GET', 'POST'])
# def teleportation():
#     basis = request.form.get('basis', 'Z') if request.method == 'POST' else 'Z'
#     counts, circuit_img, hist_img, correlation = run_teleportation_simulation(app.config['OUTPUT_DIR'], basis)
#     return render_template("teleportation.html", active_page='teleportation', counts=counts, circuit_img=circuit_img, hist_img=hist_img, correlation=correlation, current_basis=basis)
# 
# if __name__ == "__main__":
#     app.run(host='0.0.0.0', port=5000, debug=True, use_reloader=False)