# -*- coding: utf-8 -*-
"""Bell States Simulation

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16n8xaz6j24OYC9IN_8OITwBlvqHwnIFb
"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile quantum/bell_states.py
# import os
# import matplotlib
# matplotlib.use('Agg')
# import matplotlib.pyplot as plt
# from qiskit import QuantumCircuit
# from qiskit_aer import AerSimulator
# from qiskit.visualization import plot_histogram
# 
# def run_bell_simulation(output_dir, basis='Z'):
#     qc = QuantumCircuit(2, 2)
#     qc.h(0)
#     qc.cx(0, 1)
# 
#     if basis == 'X':
#         qc.h([0, 1])
# 
#     qc.measure([0, 1], [0, 1])
# 
#     circuit_path = os.path.join(output_dir, "bell_circuit.png")
#     qc.draw(output='mpl', filename=circuit_path)
#     plt.close()
# 
#     simulator = AerSimulator()
#     result = simulator.run(qc, shots=1024).result()
#     counts = dict(result.get_counts())
# 
#     total_shots = sum(counts.values())
#     correlated = counts.get('00', 0) + counts.get('11', 0)
#     correlation_pct = round((correlated / total_shots) * 100, 2)
# 
#     hist_path = os.path.join(output_dir, "bell_histogram.png")
#     plot_histogram(counts, color='#3b82f6', title=f"Bell State ({basis}-Basis)")
#     plt.savefig(hist_path, bbox_inches='tight', dpi=300)
#     plt.close()
# 
#     return counts, "bell_circuit.png", "bell_histogram.png", correlation_pct