# -*- coding: utf-8 -*-
"""DashBoard Html

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16n8xaz6j24OYC9IN_8OITwBlvqHwnIFb
"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile templates/dashboard.html
# {% extends "base.html" %}
# {% block content %}
# <div style="margin-bottom: 40px;">
#     <span class="badge rounded-pill mb-2 px-3 py-2" style="background: rgba(6, 182, 212, 0.1); color: #06b6d4; border: 1px solid rgba(6, 182, 212, 0.3);">
#         <i class="fa-solid fa-rocket me-2"></i> Qiskit Backend Active
#     </span>
#     <h1 style="margin: 8px 0 8px 0; font-size: 2.2rem;">Quantum Communication Overview</h1>
#     <p style="color: var(--text-muted); margin: 0; font-size: 1.05rem;">Select a protocol below to generate circuits and configure measurement basis.</p>
# </div>
# 
# <div class="row">
#     <div class="col-8">
#         <div class="saas-card" style="padding-bottom: 10px;">
#             <h3 style="margin: 0 0 16px 0; font-size: 1.1rem; color: var(--text-main);">Simulation Activity Overview</h3>
#             <div style="height: 250px; width: 100%;">
#                 <canvas id="activityChart"></canvas>
#             </div>
#         </div>
#     </div>
#     <div class="col-4">
#         <div class="saas-card" style="background: linear-gradient(145deg, var(--bg-card), rgba(139, 92, 246, 0.1));">
#             <div class="icon-wrapper" style="background: rgba(139, 92, 246, 0.2); color: #a78bfa; margin-bottom: 12px; height: 36px; width: 36px; font-size: 1rem;">
#                 <i class="fa-solid fa-lightbulb"></i>
#             </div>
#             <h3 style="margin: 0 0 12px 0; font-size: 1.1rem;">Quantum Fact</h3>
#             <p id="q-fact" style="color: var(--text-muted); font-size: 0.95rem; line-height: 1.6; margin-bottom: 0;">
#                 Quantum networking fundamentally shifts data transmission by encoding information in quantum states. Any attempt to intercept the communication disrupts the entanglement, immediately alerting the parties to the breach and ensuring unconditional security.
#             </p>
#         </div>
#     </div>
# </div>
# 
# <div class="row" style="margin-top: 12px;">
#     <div class="col-4">
#         <div class="saas-card">
#             <div class="icon-wrapper" style="background: rgba(59, 130, 246, 0.1); color: var(--primary);">
#                 <i class="fa-solid fa-link"></i>
#             </div>
#             <h3 style="margin: 0 0 12px 0;">Bell States</h3>
#             <p style="color: var(--text-muted); margin: 0 0 24px 0; line-height: 1.5; font-size: 0.9rem;">Configure measurement basis and calculate state correlation.</p>
#             <a href="{{ url_for('bell_states') }}" class="btn-saas btn-primary" style="display: block;">Initialize Protocol</a>
#         </div>
#     </div>
# 
#     <div class="col-4">
#         <div class="saas-card">
#             <div class="icon-wrapper" style="background: rgba(139, 92, 246, 0.1); color: var(--purple);">
#                 <i class="fa-solid fa-circle-nodes"></i>
#             </div>
#             <h3 style="margin: 0 0 12px 0;">Entanglement</h3>
#             <p style="color: var(--text-muted); margin: 0 0 24px 0; line-height: 1.5; font-size: 0.9rem;">Observe instantaneous quantum correlation across simulated space.</p>
#             <a href="{{ url_for('entanglement') }}" class="btn-saas btn-purple" style="display: block;">Initialize Protocol</a>
#         </div>
#     </div>
# 
#     <div class="col-4">
#         <div class="saas-card">
#             <div class="icon-wrapper" style="background: rgba(16, 185, 129, 0.1); color: var(--success);">
#                 <i class="fa-solid fa-bolt"></i>
#             </div>
#             <h3 style="margin: 0 0 12px 0;">Teleportation</h3>
#             <p style="color: var(--text-muted); margin: 0 0 24px 0; line-height: 1.5; font-size: 0.9rem;">Execute 3-qubit state transfer utilizing classical and quantum channels.</p>
#             <a href="{{ url_for('teleportation') }}" class="btn-saas btn-success" style="display: block;">Initialize Protocol</a>
#         </div>
#     </div>
# </div>
# {% endblock %}
# 
# {% block scripts %}
# <script>
#     document.addEventListener("DOMContentLoaded", function() {
#         const ctx = document.getElementById('activityChart').getContext('2d');
#         const gradient = ctx.createLinearGradient(0, 0, 0, 400);
#         gradient.addColorStop(0, 'rgba(6, 182, 212, 0.4)');
#         gradient.addColorStop(1, 'rgba(6, 182, 212, 0.0)');
# 
#         new Chart(ctx, {
#             type: 'line',
#             data: {
#                 labels: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun'],
#                 datasets: [{
#                     label: 'Simulations Executed',
#                     data: [120, 190, 250, 210, 310, 450],
#                     borderColor: '#06b6d4',
#                     backgroundColor: gradient,
#                     borderWidth: 2,
#                     fill: true,
#                     tension: 0.4,
#                     pointBackgroundColor: '#06b6d4',
#                     pointBorderColor: '#fff',
#                     pointRadius: 4
#                 }]
#             },
#             options: {
#                 responsive: true,
#                 maintainAspectRatio: false,
#                 plugins: { legend: { display: false } },
#                 scales: {
#                     x: { grid: { color: 'rgba(255, 255, 255, 0.05)' }, ticks: { color: '#94a3b8' } },
#                     y: { grid: { color: 'rgba(255, 255, 255, 0.05)' }, ticks: { color: '#94a3b8' } }
#                 }
#             }
#         });
#     });
# </script>
# {% endblock %}