# -*- coding: utf-8 -*-
"""Entanglement Html

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16n8xaz6j24OYC9IN_8OITwBlvqHwnIFb
"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile templates/entanglement.html
# {% extends "base.html" %}
# {% block content %}
# <div style="display: flex; justify-content: space-between; align-items: flex-end; margin-bottom: 32px;">
#     <div>
#         <h1 style="margin: 0 0 8px 0; font-size: 1.75rem;"><i class="fa-solid fa-circle-nodes" style="color: var(--purple); margin-right: 12px;"></i>Entanglement Protocol</h1>
#         <p style="color: var(--text-muted); margin: 0;">Instantaneous correlation analysis.</p>
#     </div>
# 
#     <form method="POST" style="display: flex; gap: 12px; align-items: flex-end; background: var(--bg-card); padding: 12px 20px; border-radius: 8px; border: 1px solid var(--border-color);">
#         <div>
#             <label style="display: block; font-size: 0.75rem; color: var(--text-muted); margin-bottom: 4px; text-transform: uppercase;">Measurement Basis</label>
#             <select name="basis" style="background: rgba(0,0,0,0.2); color: white; border: 1px solid var(--border-color); padding: 8px; border-radius: 6px; outline: none;">
#                 <option value="Z" {% if current_basis == 'Z' %}selected{% endif %}>Z-Basis</option>
#                 <option value="X" {% if current_basis == 'X' %}selected{% endif %}>X-Basis</option>
#             </select>
#         </div>
#         <button type="submit" class="btn-saas btn-purple" style="padding: 9px 16px;"><i class="fa-solid fa-play" style="margin-right: 6px;"></i> Execute</button>
#     </form>
# </div>
# 
# <div class="row">
#     <div class="col-6">
#         <div class="saas-card">
#             <h3 style="margin: 0 0 20px 0; font-size: 1.1rem; border-bottom: 1px solid var(--border-color); padding-bottom: 12px;">Circuit Visualization</h3>
#             <div class="img-container">
#                 <img src="{{ url_for('static', filename='outputs/' + circuit_img) }}" alt="Circuit" style="max-width: 100%; height: auto;">
#             </div>
# 
#             <div style="background: rgba(139, 92, 246, 0.1); border: 1px solid rgba(139, 92, 246, 0.2); padding: 16px; border-radius: 8px; margin-top: 20px; display: flex; justify-content: space-between; align-items: center;">
#                 <div>
#                     <h4 style="margin: 0 0 4px 0; color: #a78bfa; font-size: 0.95rem;">Entanglement Correlation</h4>
#                     <p style="margin: 0; font-size: 0.8rem; color: var(--text-muted);">Percentage of matching qubit outcomes.</p>
#                 </div>
#                 <div style="font-size: 1.5rem; font-weight: bold; color: white;">{{ correlation }}%</div>
#             </div>
#         </div>
#     </div>
# 
#     <div class="col-6">
#         <div class="saas-card">
#             <h3 style="margin: 0 0 20px 0; font-size: 1.1rem; border-bottom: 1px solid var(--border-color); padding-bottom: 12px;">Distribution (1024 Shots) | {{ current_basis }}-Basis</h3>
#             <div class="img-container">
#                 <img src="{{ url_for('static', filename='outputs/' + hist_img) }}" alt="Histogram" style="max-width: 100%; height: auto;">
#             </div>
#             <div style="margin-top: 20px;">
#                 <p style="margin: 0 0 12px 0; font-weight: 600; font-size: 0.9rem; color: var(--text-muted);">RAW STATE COUNTS</p>
#                 <div style="display: flex; gap: 12px;">
#                     {% for state, count in counts.items() %}
#                         <span class="badge-custom" style="background: rgba(139, 92, 246, 0.15); color: #a78bfa; border: 1px solid rgba(139, 92, 246, 0.3);">|{{ state }}⟩ : {{ count }}</span>
#                     {% endfor %}
#                 </div>
#             </div>
#         </div>
#     </div>
# </div>
# {% endblock %}