cd # -*- coding: utf-8 -*-
"""Environment & Directory Setup

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16n8xaz6j24OYC9IN_8OITwBlvqHwnIFb
"""

!pip install Flask qiskit qiskit-aer matplotlib pylatexenc Werkzeug==3.0.1

import os
directories = ['quantum', 'templates', 'static/css', 'static/outputs']
for dir_name in directories:
    os.makedirs(dir_name, exist_ok=True)

with open('quantum/__init__.py', 'w') as f:
    f.write('')

print("Environment and architecture successfully initialized.")