# -*- coding: utf-8 -*-
"""Final Execution

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16n8xaz6j24OYC9IN_8OITwBlvqHwnIFb
"""

from google.colab.output import eval_js

print("\n" + "="*70)
print(" 🚀 QUANTUM COMMUNICATION PLATFORM INITIALIZED")
print(" CLICK THE SECURE LINK BELOW TO OPEN THE DASHBOARD IN A NEW TAB:")
print(f" {eval_js('google.colab.kernel.proxyPort(5000)')}")
print("="*70 + "\n")

!python app.py