# -*- coding: utf-8 -*-
"""Html

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16n8xaz6j24OYC9IN_8OITwBlvqHwnIFb
"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile templates/base.html
# <!DOCTYPE html>
# <html lang="en">
# <head>
#     <meta charset="UTF-8">
#     <meta name="viewport" content="width=device-width, initial-scale=1.0">
#     <title>Quantum Communication Dashboard</title>
#     <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
#     <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">
#     <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
#     <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
#     <style>
#         .row { display: flex; flex-wrap: wrap; margin: -12px; }
#         .col-4 { width: calc(33.333% - 24px); margin: 12px; }
#         .col-6 { width: calc(50% - 24px); margin: 12px; }
#         .col-8 { width: calc(66.666% - 24px); margin: 12px; }
#         .col-12 { width: calc(100% - 24px); margin: 12px; }
#         @media (max-width: 1024px) { .col-4 { width: calc(50% - 24px); } .col-8 { width: calc(100% - 24px); } }
#         @media (max-width: 768px) { .col-4, .col-6 { width: calc(100% - 24px); } #sidebar { display: none; } }
#     </style>
# </head>
# <body>
#     <div id="wrapper">
#         <div id="sidebar">
#             <div class="brand-area">
#                 <i class="fa-solid fa-layer-group" style="color: var(--primary);"></i>
#                 Quantum Dashboard
#             </div>
#             <div style="padding: 24px 0;">
#                 <p style="padding: 0 24px; font-size: 0.75rem; text-transform: uppercase; letter-spacing: 1px; color: var(--border-color); font-weight: 700; margin-bottom: 12px;">Workspace</p>
#                 <a href="{{ url_for('dashboard') }}" class="nav-link {% if active_page == 'dashboard' %}active{% endif %}">
#                     <i class="fa-solid fa-house"></i> Overview
#                 </a>
# 
#                 <p style="padding: 0 24px; font-size: 0.75rem; text-transform: uppercase; letter-spacing: 1px; color: var(--border-color); font-weight: 700; margin: 24px 0 12px 0;">Protocols</p>
#                 <a href="{{ url_for('bell_states') }}" class="nav-link {% if active_page == 'bell' %}active{% endif %}">
#                     <i class="fa-solid fa-link"></i> Bell States
#                 </a>
#                 <a href="{{ url_for('entanglement') }}" class="nav-link {% if active_page == 'entanglement' %}active{% endif %}">
#                     <i class="fa-solid fa-circle-nodes"></i> Entanglement
#                 </a>
#                 <a href="{{ url_for('teleportation') }}" class="nav-link {% if active_page == 'teleportation' %}active{% endif %}">
#                     <i class="fa-solid fa-bolt"></i> Teleportation
#                 </a>
#             </div>
#         </div>
# 
#         <div id="page-content-wrapper">
#             <div class="top-nav">
#                 <div style="font-weight: 500; color: var(--text-muted);">
#                     Project / <span style="color: var(--text-main);">Simulation Environment</span>
#                 </div>
#                 <div style="display: flex; align-items: center; gap: 16px;">
#                     <span style="font-size: 0.85rem; color: var(--success);"><i class="fa-solid fa-circle" style="font-size: 8px; margin-right: 6px;"></i>Qiskit Aer Ready</span>
#                     <div style="width: 36px; height: 36px; border-radius: 50%; background: var(--primary); display: flex; justify-content: center; align-items: center; font-weight: bold; font-size: 0.9rem;">
#                         GS
#                     </div>
#                 </div>
#             </div>
#             <div class="content-area">
#                 {% block content %}{% endblock %}
#             </div>
#         </div>
#     </div>
#     {% block scripts %}{% endblock %}
# </body>
# </html>