# -*- coding: utf-8 -*-
"""Teleportation Simulation

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16n8xaz6j24OYC9IN_8OITwBlvqHwnIFb
"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile quantum/teleportation.py
# import os
# import matplotlib
# matplotlib.use('Agg')
# import matplotlib.pyplot as plt
# from qiskit import QuantumCircuit
# from qiskit_aer import AerSimulator
# from qiskit.visualization import plot_histogram
# 
# def run_teleportation_simulation(output_dir, basis='Z'):
#     qc = QuantumCircuit(3, 3)
#     qc.h(1)
#     qc.cx(1, 2)
#     qc.cx(0, 1)
#     qc.h(0)
# 
#     if basis == 'X':
#         qc.h([0, 1, 2])
# 
#     qc.measure([0, 1, 2], [0, 1, 2])
# 
#     circuit_path = os.path.join(output_dir, "teleportation_circuit.png")
#     qc.draw(output='mpl', filename=circuit_path)
#     plt.close()
# 
#     simulator = AerSimulator()
#     result = simulator.run(qc, shots=1024).result()
#     counts = dict(result.get_counts())
# 
#     total_shots = sum(counts.values())
#     success_states = sum([val for key, val in counts.items() if key[0] == key[2]])
#     correlation_pct = round((success_states / total_shots) * 100, 2)
# 
#     hist_path = os.path.join(output_dir, "teleportation_histogram.png")
#     plot_histogram(counts, color='#10b981', title=f"Teleportation ({basis}-Basis)")
#     plt.savefig(hist_path, bbox_inches='tight', dpi=300)
#     plt.close()
# 
#     return counts, "teleportation_circuit.png", "teleportation_histogram.png", correlation_pct