# -*- coding: utf-8 -*-
"""ui/ux

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16n8xaz6j24OYC9IN_8OITwBlvqHwnIFb
"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile static/css/style.css
# :root {
#     --bg-main: #0f172a;
#     --bg-sidebar: #1e293b;
#     --bg-card: #1e293b;
#     --border-color: #334155;
#     --text-main: #f8fafc;
#     --text-muted: #94a3b8;
#     --primary: #3b82f6;
#     --purple: #8b5cf6;
#     --success: #10b981;
# }
# 
# body {
#     background-color: var(--bg-main);
#     color: var(--text-main);
#     font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
#     margin: 0;
#     overflow-x: hidden;
# }
# 
# #wrapper { display: flex; min-height: 100vh; }
# 
# #sidebar {
#     width: 260px; background-color: var(--bg-sidebar); border-right: 1px solid var(--border-color);
#     flex-shrink: 0; display: flex; flex-direction: column;
# }
# 
# .brand-area { padding: 24px; border-bottom: 1px solid var(--border-color); font-weight: 700; font-size: 1.25rem; display: flex; align-items: center; gap: 12px; }
# 
# .nav-link { color: var(--text-muted); padding: 12px 24px; display: flex; align-items: center; gap: 12px; text-decoration: none; transition: all 0.2s; font-weight: 500; font-size: 0.95rem; }
# .nav-link:hover { color: var(--text-main); background-color: rgba(255, 255, 255, 0.05); }
# .nav-link.active { color: var(--primary); background-color: rgba(59, 130, 246, 0.1); border-right: 3px solid var(--primary); }
# 
# #page-content-wrapper { flex-grow: 1; display: flex; flex-direction: column; }
# .top-nav { height: 70px; border-bottom: 1px solid var(--border-color); background-color: var(--bg-main); display: flex; align-items: center; padding: 0 32px; justify-content: space-between; }
# .content-area { padding: 32px; }
# 
# .saas-card { background-color: var(--bg-card); border: 1px solid var(--border-color); border-radius: 12px; padding: 24px; height: 100%; transition: transform 0.2s, box-shadow 0.2s; }
# .saas-card:hover { transform: translateY(-2px); box-shadow: 0 10px 25px -5px rgba(0, 0, 0, 0.3); }
# 
# .icon-wrapper { width: 48px; height: 48px; border-radius: 10px; display: flex; align-items: center; justify-content: center; font-size: 1.25rem; margin-bottom: 20px; }
# 
# .btn-saas { display: inline-block; padding: 10px 20px; border-radius: 8px; font-weight: 600; text-decoration: none; text-align: center; transition: all 0.2s; border: none; cursor: pointer; }
# .btn-primary { background: var(--primary); color: white; }
# .btn-primary:hover { background: #2563eb; color: white;}
# .btn-purple { background: var(--purple); color: white; }
# .btn-purple:hover { background: #7c3aed; color: white;}
# .btn-success { background: var(--success); color: white; }
# .btn-success:hover { background: #059669; color: white;}
# 
# .img-container { background: white; border-radius: 8px; padding: 16px; display: flex; justify-content: center; align-items: center; margin-bottom: 16px; }
# .badge-custom { padding: 6px 12px; border-radius: 6px; font-weight: 600; font-size: 0.9rem; }