# -*- coding: utf-8 -*-
"""Grover Algorithm

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17lbiqiF1Oq_aGdPUyHuNnpAotYaJH4ej
"""



# ==========================================================
# IMPORT LIBRARIES
# ==========================================================
from qiskit import QuantumCircuit
from qiskit.primitives import StatevectorSampler
from qiskit_algorithms import Grover, AmplificationProblem
from IPython.display import display

# ==========================================================
# STUDENT DATABASE
# ==========================================================
student_database = {
    "000": {"roll":101, "name":"Arjun"},
    "001": {"roll":102, "name":"Bhavana"},
    "010": {"roll":103, "name":"Charan"},
    "011": {"roll":104, "name":"Deepika"},
    "100": {"roll":105, "name":"Eshwar"},
    "101": {"roll":106, "name":"Farah"},
    "110": {"roll":107, "name":"Gopi"},
    "111": {"roll":108, "name":"Harsha"}
}

# ==========================================================
# DISPLAY DATABASE
# ==========================================================
print("\n========== STUDENT DATABASE ==========\n")

for state, student in student_database.items():
    print(
        f"State: {state} | "
        f"Roll: {student['roll']} | "
        f"Name: {student['name']}"
    )

# ==========================================================
# CREATE ORACLE FUNCTION
# ==========================================================
def create_oracle(target):

    oracle = QuantumCircuit(3)

    # Convert target state to |111>
    for i, bit in enumerate(target):
        if bit == "0":
            oracle.x(i)

    # Phase oracle
    oracle.h(2)
    oracle.ccx(0,1,2)
    oracle.h(2)

    # Restore qubits
    for i, bit in enumerate(target):
        if bit == "0":
            oracle.x(i)

    return oracle


# ==========================================================
# USER INPUT
# ==========================================================
person = input("\nEnter student name: ")

target_state = None

for state, student in student_database.items():
    if student["name"].lower() == person.lower():
        target_state = state
        break

# ==========================================================
# CHECK STUDENT
# ==========================================================
if target_state is None:

    print("\nStudent not found!")

else:

    print("\n========== SEARCH ==========")
    print("Student :", person)
    print("State   :", target_state)
    print("Roll No :", student_database[target_state]["roll"])

    # ======================================================
    # CREATE ORACLE
    # ======================================================
    oracle = create_oracle(target_state)

    print("\n========== ORACLE CIRCUIT ==========\n")
    display(oracle.draw("mpl"))

    # ======================================================
    # CREATE AMPLIFICATION PROBLEM
    # ======================================================
    problem = AmplificationProblem(
        oracle=oracle,
        is_good_state=[target_state]
    )

    # ======================================================
    # CREATE SAMPLER
    # ======================================================
    sampler = StatevectorSampler()

    # ======================================================
    # CREATE GROVER
    # ======================================================
    grover = Grover(
        sampler=sampler
    )

    # ======================================================
    # RUN GROVER
    # ======================================================
    result = grover.amplify(problem)

    # ======================================================
    # DISPLAY RESULT
    # ======================================================
    found_state = result.top_measurement

    print("\n========== GROVER RESULT ==========\n")
    print("Measured State :", found_state)
    print("Student Name   :", student_database[found_state]["name"])
    print("Roll Number    :", student_database[found_state]["roll"])
    print("Valid Solution :", result.oracle_evaluation)
    print("Iterations     :", result.iterations)