# -*- coding: utf-8 -*-
"""Quanum Optimization

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lr0ApGXvhzFtV7P1gv5gSBuifebmBxXU
"""



import warnings
from scipy.sparse import SparseEfficiencyWarning
warnings.filterwarnings("ignore", category=SparseEfficiencyWarning)

import networkx as nx
import matplotlib.pyplot as plt

from qiskit_algorithms import QAOA
from qiskit_algorithms.optimizers import COBYLA
from qiskit.primitives import StatevectorSampler

from qiskit_optimization.applications import Maxcut
from qiskit_optimization.translators import to_ising
from qiskit_optimization.algorithms import MinimumEigenOptimizer

from qiskit.circuit.library import QAOAAnsatz

# ============================================================
# STEP 1 : Create Graph
# ============================================================

graph = nx.Graph()

graph.add_edges_from([
    (0,1),
    (1,2),
    (2,3),
    (3,0)
])

print("="*60)
print("GRAPH INFORMATION")
print("="*60)

print("Nodes :", graph.nodes())
print("Edges :", graph.edges())

plt.figure(figsize=(5,5))

nx.draw(
    graph,
    with_labels=True,
    node_color="skyblue",
    node_size=900,
    font_size=14,
    font_weight="bold"
)

plt.title("Max-Cut Graph")
plt.show()

# ============================================================
# STEP 2 : Convert to Quadratic Program
# ============================================================

maxcut = Maxcut(graph)

qp = maxcut.to_quadratic_program()

print("\n")
print("="*60)
print("QUADRATIC PROGRAM")
print("="*60)
print(qp)

# ============================================================
# STEP 3 : Convert into Ising Hamiltonian
# ============================================================

operator, offset = to_ising(qp)

print("\nOffset :", offset)

# ============================================================
# STEP 4 : QAOA Ansatz Circuit
# ============================================================

ansatz = QAOAAnsatz(
    cost_operator=operator,
    reps=2
)

print("\n")
print("="*60)
print("QAOA ANSATZ CIRCUIT")
print("="*60)

print(ansatz.decompose().draw(output="text"))

# ============================================================
# STEP 5 : Define Optimizer
# ============================================================

optimizer = COBYLA(maxiter=100)

sampler = StatevectorSampler()

# ============================================================
# STEP 6 : Build QAOA
# ============================================================

qaoa = QAOA(
    sampler=sampler,
    optimizer=optimizer,
    reps=2
)

# ============================================================
# STEP 7 : Optimize
# ============================================================

result = qaoa.compute_minimum_eigenvalue(operator)

print("\n")
print("="*60)
print("QAOA OPTIMIZATION RESULT")
print("="*60)

print("Minimum Eigenvalue :", result.eigenvalue.real)

print("\nOptimal Parameters")

for i, value in enumerate(result.optimal_point):
    print(f"θ{i+1} = {value:.6f}")

# ============================================================
# STEP 8 : Solve MaxCut
# ============================================================

solver = MinimumEigenOptimizer(qaoa)

solution = solver.solve(qp)

# ============================================================
# STEP 9 : Final Results
# ============================================================

print("\n")
print("="*60)
print("FINAL MAX-CUT SOLUTION")
print("="*60)

print("Optimal Bitstring :", solution.x)

print("Maximum Cut Value :", solution.fval)

print("Status            :", solution.status)

# ============================================================
# STEP 10 : Partition Visualization
# ============================================================

colors = []

for bit in solution.x:
    if bit == 0:
        colors.append("skyblue")
    else:
        colors.append("orange")

plt.figure(figsize=(5,5))

nx.draw(
    graph,
    with_labels=True,
    node_color=colors,
    node_size=900,
    font_size=14,
    font_weight="bold"
)

plt.title("Optimal Max-Cut Partition")
plt.show()

# ============================================================
# STEP 11 : Research Report
# ============================================================

print("\n")
print("="*70)
print("                QAOA RESEARCH REPORT")
print("="*70)

print(f"Number of Nodes          : {graph.number_of_nodes()}")
print(f"Number of Edges          : {graph.number_of_edges()}")
print(f"Optimizer                : COBYLA")
print(f"Maximum Iterations       : 100")
print(f"QAOA Layers (p)          : 2")
print(f"Quantum Primitive        : StatevectorSampler")
print(f"Minimum Eigenvalue       : {result.eigenvalue.real:.6f}")
print(f"Maximum Cut             : {solution.fval}")
print(f"Optimal Bitstring        : {solution.x}")
print(f"Optimization Status      : {solution.status}")

print("="*70)