# -*- coding: utf-8 -*-
"""VQC

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GhlFnFapc2wUyyAN1KS4K55D8vL4P5bV

# Variational Quantum Classifier
"""

!pip install qiskit qiskit-aer qiskit-machine-learning qiskit-algorithms scikit-learn matplotlib pandas -q

import numpy as np
import matplotlib.pyplot as plt

from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.metrics import accuracy_score, classification_report, ConfusionMatrixDisplay

from qiskit.circuit.library import ZZFeatureMap, RealAmplitudes
from qiskit.primitives import StatevectorSampler
from qiskit_algorithms.optimizers import COBYLA
from qiskit_machine_learning.algorithms.classifiers import VQC

iris = load_iris()

X = iris.data
y = iris.target

print("Dataset Shape:", X.shape)

scaler = StandardScaler()
X = scaler.fit_transform(X)

pca = PCA(n_components=2)

X = pca.fit_transform(X)

print("Reduced Shape:", X.shape)

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

feature_map = ZZFeatureMap(
    feature_dimension=2,
    reps=2
)

ansatz = RealAmplitudes(
    num_qubits=2,
    reps=2
)

optimizer = COBYLA(maxiter=100)

sampler = StatevectorSampler()

vqc = VQC(
    sampler=sampler,
    feature_map=feature_map,
    ansatz=ansatz,
    optimizer=optimizer
)

print("Training...")

vqc.fit(X_train, y_train)

print("Training Complete!")

predictions = vqc.predict(X_test)

accuracy = accuracy_score(y_test, predictions)

print("Accuracy:", accuracy)

print(classification_report(y_test, predictions))

ConfusionMatrixDisplay.from_predictions(
    y_test,
    predictions,
    display_labels=iris.target_names,
    cmap="Blues"
)

plt.show()

print(feature_map.draw())

ansatz.draw(output="text")