# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1t1CWtdfvZqzJCgejFarOiYGd50I3SAGe
"""

# Commented out IPython magic to ensure Python compatibility.
# %%bash
# npx create-next-app@latest hqic-frontend
# # Choose: TypeScript (Yes), ESLint (Yes), Tailwind CSS (Yes), App Router (Yes)
# cd hqic-frontend
# npm install framer-motion lucide-react recharts clsx tailwind-merge

# Commented out IPython magic to ensure Python compatibility.
# %%writefile /content/hqic-frontend/app/globals.css
# @tailwind base;
# @tailwind components;
# @tailwind utilities;
# 
# :root {
#   --background: #050816;
#   --primary-cyan: #00f3ff;
#   --primary-purple: #bc13fe;
# }
# 
# body {
#   background-color: var(--background);
#   background-image:
#     radial-gradient(circle at 15% 50%, rgba(0, 243, 255, 0.08), transparent 30%),
#     radial-gradient(circle at 85% 30%, rgba(188, 19, 254, 0.08), transparent 30%);
#   color: #ffffff;
#   min-height: 100vh;
# }
# 
# /* Premium Glassmorphism */
# .glass-panel {
#   background: rgba(255, 255, 255, 0.02);
#   backdrop-filter: blur(16px);
#   -webkit-backdrop-filter: blur(16px);
#   border: 1px solid rgba(0, 243, 255, 0.15);
#   border-radius: 16px;
#   box-shadow: 0 4px 30px rgba(0, 0, 0, 0.5);
#   transition: all 0.3s ease;
# }
# 
# .glass-panel:hover {
#   border-color: rgba(188, 19, 254, 0.4);
#   box-shadow: 0 8px 40px rgba(188, 19, 254, 0.15), inset 0 0 20px rgba(0, 243, 255, 0.05);
# }
# 
# /* Neon Text Gradients */
# .text-gradient-cyan {
#   background: linear-gradient(90deg, #00f3ff, #0077ff);
#   -webkit-background-clip: text;
#   -webkit-text-fill-color: transparent;
#   text-shadow: 0 0 20px rgba(0, 243, 255, 0.4);
# }
# 
# .text-gradient-purple {
#   background: linear-gradient(90deg, #bc13fe, #ff00ea);
#   -webkit-background-clip: text;
#   -webkit-text-fill-color: transparent;
#   text-shadow: 0 0 20px rgba(188, 19, 254, 0.4);
# }
# 
# /* Quantum Circuit Animated Line */
# .quantum-line {
#   height: 2px;
#   background: linear-gradient(90deg, transparent, #00f3ff, #bc13fe, transparent);
#   background-size: 200% 100%;
#   animation: pulse-line 3s infinite linear;
# }
# 
# @keyframes pulse-line {
#   0% { background-position: 100% 0; }
#   100% { background-position: -100% 0; }
# }

# Commented out IPython magic to ensure Python compatibility.
# %%writefile /content/hqic-frontend/tailwind.config.ts
# import type { Config } from "tailwindcss";
# 
# const config: Config = {
#   content: [
#     "./pages/**/*.{js,ts,jsx,tsx,mdx}",
#     "./components/**/*.{js,ts,jsx,tsx,mdx}",
#     "./app/**/*.{js,ts,jsx,tsx,mdx}",
#   ],
#   theme: {
#     extend: {
#       colors: {
#         background: "#050816",
#         cyan: {
#           400: "#00f3ff",
#         },
#         purple: {
#           500: "#bc13fe",
#         }
#       },
#       fontFamily: {
#         sans: ['var(--font-inter)'],
#         mono: ['var(--font-jetbrains-mono)'],
#       }
#     },
#   },
#   plugins: [],
# };
# export default config;

# Commented out IPython magic to ensure Python compatibility.
# %%writefile /content/hqic-frontend/app/page.tsx
# "use client";
# 
# import React, { useState } from 'react';
# import { motion } from 'framer-motion';
# import {
#   Activity, Camera, Cpu, Database, Eye, History,
#   Settings, Image as ImageIcon, LineChart, Network,
#   Layers, PlayCircle
# } from 'lucide-react';
# import { LineChart as RechartsLine, Line, XAxis, YAxis, Tooltip, ResponsiveContainer } from 'recharts';
# 
# const menuItems = [
#   { id: 'dashboard', icon: Activity, label: 'Dashboard' },
#   { id: 'dataset', icon: Database, label: 'Dataset' },
#   { id: 'upload', icon: ImageIcon, label: 'Upload Image' },
#   { id: 'camera', icon: Camera, label: 'Live Camera' },
#   { id: 'video', icon: PlayCircle, label: 'Video Analysis' },
#   { id: 'quantum', icon: Network, label: 'Quantum Circuit' },
#   { id: 'cnn', icon: Layers, label: 'CNN Features' },
#   { id: 'analytics', icon: LineChart, label: 'Analytics' },
#   { id: 'performance', icon: Cpu, label: 'Model Performance' },
#   { id: 'explainability', icon: Eye, label: 'Explainability' },
#   { id: 'history', icon: History, label: 'Prediction History' },
#   { id: 'settings', icon: Settings, label: 'Settings' },
# ];
# 
# const mockData = [
#   { name: 'Epoch 1', acc: 40, qml_acc: 45 },
#   { name: 'Epoch 5', acc: 60, qml_acc: 75 },
#   { name: 'Epoch 10', acc: 75, qml_acc: 92 },
#   { name: 'Epoch 15', acc: 85, qml_acc: 97 },
#   { name: 'Epoch 20', acc: 88, qml_acc: 98.7 },
# ];
# 
# export default function Dashboard() {
#   const [activeTab, setActiveTab] = useState('dashboard');
# 
#   return (
#     <div className="flex h-screen overflow-hidden text-white font-sans">
# 
#       {/* LEFT SIDEBAR */}
#       <motion.aside
#         initial={{ x: -250 }}
#         animate={{ x: 0 }}
#         className="w-72 glass-panel border-l-0 border-y-0 rounded-none flex flex-col p-6 z-10"
#       >
#         <div className="flex items-center gap-3 mb-10">
#           <div className="w-10 h-10 rounded-full border border-cyan-400 flex items-center justify-center shadow-[0_0_15px_rgba(0,243,255,0.5)]">
#             <span className="text-xl">⚛️</span>
#           </div>
#           <h2 className="text-lg font-bold tracking-wider text-gradient-cyan">HQIC SYSTEM</h2>
#         </div>
# 
#         <nav className="flex-1 space-y-2 overflow-y-auto no-scrollbar">
#           {menuItems.map((item) => (
#             <button
#               key={item.id}
#               onClick={() => setActiveTab(item.id)}
#               className={`w-full flex items-center gap-4 px-4 py-3 rounded-lg transition-all duration-300 ${
#                 activeTab === item.id
#                   ? 'bg-gradient-to-r from-cyan-400/20 to-purple-500/20 border border-cyan-400/50 shadow-[0_0_15px_rgba(188,19,254,0.2)]'
#                   : 'hover:bg-white/5 text-gray-400 hover:text-white'
#               }`}
#             >
#               <item.icon size={20} className={activeTab === item.id ? 'text-cyan-400' : ''} />
#               <span className="font-medium">{item.label}</span>
#             </button>
#           ))}
#         </nav>
# 
#         <div className="mt-8 pt-6 border-t border-cyan-400/20">
#           <div className="text-xs font-mono text-gray-400 space-y-2">
#             <div className="flex justify-between"><span>STATUS:</span> <span className="text-green-400 drop-shadow-[0_0_5px_#4ade80]">ONLINE</span></div>
#             <div className="flex justify-between"><span>BACKEND:</span> <span className="text-cyan-400">lightning.qubit</span></div>
#             <div className="flex justify-between"><span>DEVICE:</span> <span className="text-purple-400">RTX 4090 (API)</span></div>
#           </div>
#         </div>
#       </motion.aside>
# 
#       {/* MAIN DASHBOARD CONTENT */}
#       <main className="flex-1 p-8 overflow-y-auto relative">
#         {/* Animated Background Elements */}
#         <div className="fixed top-20 right-20 w-96 h-96 bg-cyan-500/10 rounded-full blur-[120px] -z-10 animate-pulse"></div>
#         <div className="fixed bottom-20 left-[20%] w-96 h-96 bg-purple-500/10 rounded-full blur-[120px] -z-10 animate-pulse delay-1000"></div>
# 
#         <motion.div
#           initial={{ opacity: 0, y: 20 }}
#           animate={{ opacity: 1, y: 0 }}
#           transition={{ duration: 0.5 }}
#         >
#           {/* HERO HEADER */}
#           <header className="mb-12 text-center mt-6">
#             <h1 className="text-5xl font-black mb-4 tracking-tight">
#               <span className="text-gradient-cyan">HYBRID QUANTUM</span> <span className="text-gradient-purple">INTELLIGENCE</span>
#             </h1>
#             <p className="text-gray-400 font-mono tracking-widest uppercase text-sm">
#               Real-Time Environmental Scene Intelligence using Hybrid QML
#             </p>
#             <div className="quantum-line w-1/3 mx-auto mt-6"></div>
#           </header>
# 
#           {/* TOP STATS ROW */}
#           <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6 mb-8">
#             <StatCard title="Images Processed" value="1.4M" subtitle="+2,340 this hour" color="text-cyan-400" />
#             <StatCard title="Quantum Accuracy" value="98.7%" subtitle="Validation Set" color="text-green-400" />
#             <StatCard title="System FPS" value="124" subtitle="Latency: 8ms" color="text-cyan-400" />
#             <StatCard title="Quantum Inf. Time" value="2.1ms" subtitle="default.qubit" color="text-purple-400" />
#           </div>
# 
#           {/* LOWER PANELS */}
#           <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
# 
#             {/* LIVE CAMERA MOCK */}
#             <div className="lg:col-span-2 glass-panel p-6 h-[450px] flex flex-col">
#               <div className="flex justify-between items-center mb-4">
#                 <h3 className="font-bold text-gray-300 tracking-wider">LIVE SENSOR TELEMETRY</h3>
#                 <span className="flex items-center gap-2 text-xs font-mono text-red-400">
#                   <div className="w-2 h-2 bg-red-500 rounded-full animate-pulse shadow-[0_0_10px_red]"></div>
#                   REC
#                 </span>
#               </div>
#               <div className="flex-1 border border-cyan-400/20 rounded-lg flex items-center justify-center bg-black/40 relative overflow-hidden">
#                 {/* Target Reticle */}
#                 <div className="absolute w-32 h-32 border-2 border-cyan-400/30 rounded-full flex items-center justify-center">
#                   <div className="w-1 h-1 bg-cyan-400 rounded-full shadow-[0_0_10px_#00f3ff]"></div>
#                 </div>
#                 <p className="font-mono text-cyan-400/50 absolute bottom-4 left-4">AWAITING VIDEO STREAM...</p>
#               </div>
#             </div>
# 
#             {/* PERFORMANCE CHART */}
#             <div className="glass-panel p-6 h-[450px] flex flex-col">
#               <h3 className="font-bold text-gray-300 tracking-wider mb-6">MODEL PERFORMANCE</h3>
#               <div className="flex-1 w-full">
#                 <ResponsiveContainer width="100%" height="100%">
#                   <RechartsLine data={mockData}>
#                     <XAxis dataKey="name" stroke="#4b5563" fontSize={12} tickLine={false} />
#                     <YAxis stroke="#4b5563" fontSize={12} tickLine={false} />
#                     <Tooltip
#                       contentStyle={{ backgroundColor: 'rgba(5,8,22,0.9)', border: '1px solid rgba(0,243,255,0.2)', borderRadius: '8px' }}
#                       itemStyle={{ color: '#00f3ff' }}
#                     />
#                     <Line type="monotone" dataKey="qml_acc" name="Hybrid QML" stroke="#bc13fe" strokeWidth={3} dot={{ fill: '#bc13fe', r: 4 }} />
#                     <Line type="monotone" dataKey="acc" name="Standard CNN" stroke="#00f3ff" strokeWidth={2} strokeDasharray="5 5" />
#                   </RechartsLine>
#                 </ResponsiveContainer>
#               </div>
#             </div>
# 
#           </div>
#         </motion.div>
#       </main>
#     </div>
#   );
# }
# 
# // Reusable Stat Card Component
# function StatCard({ title, value, subtitle, color }: { title: string, value: string, subtitle: string, color: string }) {
#   return (
#     <div className="glass-panel p-6 group cursor-pointer">
#       <h4 className="text-gray-400 text-xs font-bold tracking-widest uppercase mb-2">{title}</h4>
#       <div className={`text-4xl font-mono font-black ${color} drop-shadow-[0_0_15px_currentColor] mb-2`}>
#         {value}
#       </div>
#       <p className="text-gray-500 text-xs font-mono">{subtitle}</p>
#     </div>
#   );
# }

