# -*- coding: utf-8 -*-
"""Camera Screen

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rOG3w4SfiHAoNZ_XJ_SLsOm2dxjmFG8X
"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile deployment/camera.py
# import threading
# import time
# from typing import Optional, Tuple
# 
# import cv2
# import numpy as np
# 
# from utils.logger import get_logger
# 
# logger = get_logger(__name__)
# 
# class ThreadedWebcam:
#     """
#     Thread-safe implementation of OpenCV webcam capture.
#     Runs I/O operations in a background thread to prevent UI blocking
#     and maintain high FPS.
#     """
#     def __init__(self, src: int = 0):
#         self.src = src
#         self.stream = cv2.VideoCapture(self.src)
#         self.stream.set(cv2.CAP_PROP_FRAME_WIDTH, 640)
#         self.stream.set(cv2.CAP_PROP_FRAME_HEIGHT, 480)
# 
#         if not self.stream.isOpened():
#             logger.error(f"Failed to open webcam source {self.src}")
#             raise RuntimeError(f"Webcam {self.src} not accessible.")
# 
#         self.grabbed, self.frame = self.stream.read()
#         self.stopped = False
#         self.lock = threading.Lock()
# 
#         # Start the background thread
#         self.thread = threading.Thread(target=self._update, args=(), daemon=True)
#         self.thread.start()
#         logger.info("ThreadedWebcam initialized and running.")
# 
#     def _update(self) -> None:
#         """Continuously pulls frames from the camera."""
#         while not self.stopped:
#             grabbed, frame = self.stream.read()
#             with self.lock:
#                 self.grabbed = grabbed
#                 self.frame = frame
#             # Tiny sleep to prevent high CPU usage in the thread
#             time.sleep(0.01)
# 
#     def read(self) -> Tuple[bool, Optional[np.ndarray]]:
#         """Returns the most recent frame."""
#         with self.lock:
#             if not self.grabbed or self.frame is None:
#                 return False, None
#             return True, self.frame.copy()
# 
#     def stop(self) -> None:
#         """Safely terminates the background thread and releases hardware."""
#         self.stopped = True
#         if self.thread.is_alive():
#             self.thread.join()
#         self.stream.release()
#         logger.info("ThreadedWebcam stopped and hardware released.")