# -*- coding: utf-8 -*-
"""config

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qot_5u1i6WcQWlJmVZzUPri7eTLmkrHg
"""

import torch
from torch.utils.data import DataLoader, Dataset
from torchvision import transforms, datasets

# ModelConfig and get_logger are defined in previous cells and are globally available.
# from config.settings import ModelConfig
# from utils.logger import get_logger

logger = get_logger(__name__)

class QuantumImageDataLoader:
    """Handles image preprocessing and data loading."""

    def __init__(self, config: ModelConfig):
        self.config = config
        self.transform = transforms.Compose([
            transforms.Resize(self.config.image_size),
            transforms.ToTensor(),
            transforms.Normalize(mean=[0.5], std=[0.5])
        ])

    def get_loaders(self) -> Tuple[DataLoader, DataLoader]:
        """Returns train and validation DataLoaders."""
        logger.info(f"Loading data from {self.config.data_dir}")
        # Insert your existing dataset logic here.
        # Example using ImageFolder:
        train_dataset = datasets.ImageFolder(f"{self.config.data_dir}/train", transform=self.transform)
        val_dataset = datasets.ImageFolder(f"{self.config.data_dir}/val", transform=self.transform)

        train_loader = DataLoader(train_dataset, batch_size=self.config.batch_size, shuffle=True)
        val_loader = DataLoader(val_dataset, batch_size=self.config.batch_size, shuffle=False)

        return train_loader, val_loader

import torch
import torch.nn as nn
# get_logger is defined in a previous cell and is globally available.
# from utils.logger import get_logger

logger = get_logger(__name__)

class ClassicalFeatureExtractor(nn.Module):
    """Classical CNN to reduce image dimensionality before the quantum circuit."""

    def __init__(self, output_dim: int):
        super().__init__()
        logger.info(f"Initializing ClassicalFeatureExtractor with output_dim={output_dim}")
        # Insert your existing CNN layers here
        self.network = nn.Sequential(
            nn.Conv2d(3, 16, kernel_size=3, stride=1, padding=1),
            nn.ReLU(),
            nn.MaxPool2d(2),
            nn.Flatten(),
            nn.Linear(16 * 32 * 32, output_dim) # Example dimensions
        )

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        return self.network(x)

import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader
# ModelConfig and get_logger are defined in previous cells and are globally available.
# from config.settings import ModelConfig
# from utils.logger import get_logger
import os

logger = get_logger(__name__)

class HybridModelTrainer:
    """Handles the training loop, loss computation, and checkpointing."""

    def __init__(self, model: nn.Module, config: ModelConfig):
        self.model = model
        self.config = config
        self.device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
        self.model.to(self.device)

        self.criterion = nn.CrossEntropyLoss()
        self.optimizer = optim.Adam(self.model.parameters(), lr=config.learning_rate)

        os.makedirs(self.config.checkpoint_dir, exist_ok=True)

    def train(self, train_loader: DataLoader, val_loader: DataLoader):
        logger.info(f"Starting training on device: {self.device}")

        for epoch in range(self.config.epochs):
            self.model.train()
            running_loss = 0.0

            for batch_idx, (inputs, targets) in enumerate(train_loader):
                inputs, targets = inputs.to(self.device), targets.to(self.device)

                self.optimizer.zero_grad()
                outputs = self.model(inputs)
                loss = self.criterion(outputs, targets)

                loss.backward()
                self.optimizer.step()
                running_loss += loss.item()

            avg_loss = running_loss / len(train_loader)
            logger.info(f"Epoch [{epoch+1}/{self.config.epochs}] - Loss: {avg_loss:.4f}")

            # Save checkpoint
            torch.save(self.model.state_dict(), f"{self.config.checkpoint_dir}/model_epoch_{epoch+1}.pt")

print(f"Current config.data_dir: {config.data_dir}")

import os

# Get the data_dir from the config object (assuming config is still in scope)
data_dir_path = config.data_dir

print(f"Checking contents of: {data_dir_path}")

# Check if the base data directory exists
if not os.path.exists(data_dir_path):
    print(f"Error: Base data directory does not exist: {data_dir_path}")
elif not os.path.isdir(data_dir_path):
    print(f"Error: Base data path is not a directory: {data_dir_path}")
else:
    print(f"Contents of {data_dir_path}:")
    try:
        for item in os.listdir(data_dir_path):
            print(f"- {item}")
    except Exception as e:
        print(f"Could not list contents: {e}")

# Check specifically for 'train' and 'val' subdirectories
train_path = os.path.join(data_dir_path, 'train')
val_path = os.path.join(data_dir_path, 'val')

print(f"\nVerifying 'train' directory: {train_path}")
if os.path.exists(train_path):
    print(f"'train' directory exists. Is it a directory? {os.path.isdir(train_path)}")
    if os.path.isdir(train_path):
        try:
            train_contents = os.listdir(train_path)
            print(f"'train' directory contains {len(train_contents)} items (first 5): {train_contents[:5]}")
        except Exception as e:
            print(f"Could not list contents of 'train' directory: {e}")
else:
    print(f"'train' directory DOES NOT EXIST at: {train_path}")

print(f"\nVerifying 'val' directory: {val_path}")
if os.path.exists(val_path):
    print(f"'val' directory exists. Is it a directory? {os.path.isdir(val_path)}")
    if os.path.isdir(val_path):
        try:
            val_contents = os.listdir(val_path)
            print(f"'val' directory contains {len(val_contents)} items (first 5): {val_contents[:5]}")
        except Exception as e:
            print(f"Could not list contents of 'val' directory: {e}")
else:
    print(f"'val' directory DOES NOT EXIST at: {val_path}")