# -*- coding: utf-8 -*-
"""Feature Reduction

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DoIoQCZVh9bqPQtNjom8uiCqxHNKgkEV
"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile models/classical/feature_extractor.py
# import torch
# import torch.nn as nn
# import torchvision.models as models
# from typing import List, Optional
# from utils.logger import get_logger
# 
# logger = get_logger(__name__)
# 
# class ResidualLinearBlock(nn.Module):
#     """
#     A single block for feature reduction featuring a residual connection,
#     configurable normalization (BatchNorm/LayerNorm), and Dropout.
#     """
#     def __init__(self, in_dim: int, out_dim: int, dropout_rate: float, norm_type: str):
#         super().__init__()
#         self.fc = nn.Linear(in_dim, out_dim)
# 
#         if norm_type == 'batch':
#             self.norm = nn.BatchNorm1d(out_dim)
#         elif norm_type == 'layer':
#             self.norm = nn.LayerNorm(out_dim)
#         else:
#             raise ValueError(f"Unsupported norm_type: {norm_type}. Use 'batch' or 'layer'.")
# 
#         self.activation = nn.GELU()
#         self.dropout = nn.Dropout(dropout_rate)
# 
#         # Linear projection for the residual shortcut if dimensions change
#         self.shortcut = nn.Identity() if in_dim == out_dim else nn.Linear(in_dim, out_dim, bias=False)
# 
#     def forward(self, x: torch.Tensor) -> torch.Tensor:
#         residual = self.shortcut(x)
#         out = self.fc(x)
#         out = self.norm(out)
#         out = out + residual  # Add residual before activation
#         out = self.activation(out)
#         out = self.dropout(out)
#         return out
# 
# 
# class FeatureReductionHead(nn.Module):
#     """
#     Configurable module to reduce high-dimensional classical features
#     down to the exact number of qubits required for quantum encoding.
#     Example: 2048 -> 256 -> 64 -> 4
#     """
#     def __init__(
#         self,
#         in_features: int,
#         out_features: int,
#         hidden_dims: List[int],
#         dropout_rate: float = 0.3,
#         norm_type: str = 'layer'
#     ):
#         super().__init__()
#         logger.info(f"Building Reduction Head: {in_features} -> {hidden_dims} -> {out_features}")
# 
#         layers = []
#         current_dim = in_features
# 
#         # Build residual hidden layers dynamically
#         for h_dim in hidden_dims:
#             layers.append(ResidualLinearBlock(current_dim, h_dim, dropout_rate, norm_type))
#             current_dim = h_dim
# 
#         self.blocks = nn.Sequential(*layers)
# 
#         # Final projection to quantum embedding space
#         self.final_norm = nn.BatchNorm1d(current_dim) if norm_type == 'batch' else nn.LayerNorm(current_dim)
#         self.final_fc = nn.Linear(current_dim, out_features)
# 
#         # Tanh bounds outputs to [-1, 1] for stable Quantum Angle Encoding
#         self.final_act = nn.Tanh()
# 
#         self._initialize_weights()
# 
#     def _initialize_weights(self) -> None:
#         """Applies Kaiming Normal initialization to linear layers."""
#         for m in self.modules():
#             if isinstance(m, nn.Linear):
#                 nn.init.kaiming_normal_(m.weight, nonlinearity='linear')
#                 if m.bias is not None:
#                     nn.init.constant_(m.bias, 0)
#         logger.info("Applied Kaiming Normal weight initialization to Reduction Head.")
# 
#     def forward(self, x: torch.Tensor) -> torch.Tensor:
#         x = self.blocks(x)
#         x = self.final_norm(x)
#         x = self.final_fc(x)
#         return self.final_act(x)
# 
# 
# class ClassicalFeatureExtractor(nn.Module):
#     """
#     Robust classical feature extractor serving as the front-end for the
#     Hybrid Quantum Classifier.
#     """
# 
#     SUPPORTED_BACKBONES = {
#         'resnet50',
#         'efficientnet_b0',
#         'efficientnet_v2_s',
#         'convnext_tiny',
#         'mobilenet_v3'
#     }
# 
#     def __init__(
#         self,
#         output_dim: int,
#         backbone_name: str = 'resnet50',
#         hidden_dims: Optional[List[int]] = None,
#         dropout_rate: float = 0.3,
#         norm_type: str = 'layer'
#     ):
#         """
#         Initializes the feature extractor.
# 
#         Args:
#             output_dim: The target dimension matching `config.n_qubits`.
#             backbone_name: The CNN architecture to load.
#             hidden_dims: Dimensions of intermediate reduction layers (e.g., [256, 64]).
#             dropout_rate: Regularization rate for the reduction head.
#             norm_type: Normalization strategy ('batch' or 'layer').
#         """
#         super().__init__()
#         self.backbone_name = backbone_name.lower()
#         self.output_dim = output_dim
# 
#         # Default architecture for smooth step-down if not specified
#         if hidden_dims is None:
#             hidden_dims = [256, 64]
# 
#         if self.backbone_name not in self.SUPPORTED_BACKBONES:
#             raise ValueError(f"Backbone '{self.backbone_name}' not supported. Choose from {self.SUPPORTED_BACKBONES}")
# 
#         logger.info(f"Initializing {self.backbone_name.upper()} as Classical Feature Extractor...")
#         self.backbone = self._build_backbone()
# 
#         # Automatically freeze backbone layers for Transfer Learning
#         self._freeze_backbone()
# 
#         # Dynamically determine in_features for the reduction head
#         in_features = self._get_feature_dim()
#         logger.info(f"Backbone flattened feature dimension detected as: {in_features}")
# 
#         # Build the heavily regularized, residual reduction head
#         self.reduction_head = FeatureReductionHead(
#             in_features=in_features,
#             out_features=self.output_dim,
#             hidden_dims=hidden_dims,
#             dropout_rate=dropout_rate,
#             norm_type=norm_type
#         )
# 
#     def _build_backbone(self) -> nn.Module:
#         """Loads pretrained weights and strips the classification head."""
#         if self.backbone_name == 'resnet50':
#             model = models.resnet50(weights=models.ResNet50_Weights.DEFAULT)
#             model.fc = nn.Identity()
# 
#         elif self.backbone_name == 'efficientnet_b0':
#             model = models.efficientnet_b0(weights=models.EfficientNet_B0_Weights.DEFAULT)
#             model.classifier = nn.Identity()
# 
#         elif self.backbone_name == 'efficientnet_v2_s':
#             model = models.efficientnet_v2_s(weights=models.EfficientNet_V2_S_Weights.DEFAULT)
#             model.classifier = nn.Identity()
# 
#         elif self.backbone_name == 'convnext_tiny':
#             model = models.convnext_tiny(weights=models.ConvNeXt_Tiny_Weights.DEFAULT)
#             model.classifier = nn.Identity()
# 
#         elif self.backbone_name == 'mobilenet_v3':
#             model = models.mobilenet_v3_large(weights=models.MobileNet_V3_Large_Weights.DEFAULT)
#             model.classifier = nn.Identity()
# 
#         return model
# 
#     def _freeze_backbone(self) -> None:
#         """Freezes all parameters in the backbone network."""
#         for param in self.backbone.parameters():
#             param.requires_grad = False
#         logger.info("Backbone layers frozen successfully.")
# 
#     def _get_feature_dim(self) -> int:
#         """Passes a dummy tensor to securely extract the exact intermediate feature dimension."""
#         dummy_input = torch.randn(1, 3, 64, 64)
# 
#         with torch.no_grad():
#             out = self.backbone(dummy_input)
#             out = torch.flatten(out, 1)
# 
#         return out.shape[1]
# 
#     def forward(self, x: torch.Tensor) -> torch.Tensor:
#         """
#         Forward pass converting batched images into quantum-ready state vectors.
#         """
#         x = self.backbone(x)
#         x = torch.flatten(x, 1)
#         x = self.reduction_head(x)
#         return x