# -*- coding: utf-8 -*-
"""Hybrid Model

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xScJTdlZs8NM6h7ZYeBLt3hT7I6E7IBJ
"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile models/hybrid/classifier.py
# from typing import List, Optional
# 
# import torch
# import torch.nn as nn
# 
# from config.settings import ModelConfig
# from models.classical.feature_extractor import ClassicalFeatureExtractor
# from models.quantum.circuit import VariationalQuantumCircuit
# from utils.logger import get_logger
# 
# logger = get_logger(__name__)
# 
# class FeatureAttentionBlock(nn.Module):
#     """
#     1D Self-Attention mechanism applied to classical features before quantum encoding.
#     Utilizes LayerNorm, Dropout, and Residual Connections to refine the feature
#     representation prior to parameterized quantum circuit embedding.
#     """
#     def __init__(self, embed_dim: int, dropout: float = 0.1):
#         super().__init__()
#         # num_heads=1 ensures compatibility with any n_qubits dimension (e.g., 4, 10)
#         self.attention = nn.MultiheadAttention(
#             embed_dim, num_heads=1, dropout=dropout, batch_first=True
#         )
#         self.norm1 = nn.LayerNorm(embed_dim)
#         self.norm2 = nn.LayerNorm(embed_dim)
# 
#         # Feed-forward network (FFN)
#         self.ffn = nn.Sequential(
#             nn.Linear(embed_dim, embed_dim * 2),
#             nn.GELU(),
#             nn.Dropout(dropout),
#             nn.Linear(embed_dim * 2, embed_dim)
#         )
#         self.dropout = nn.Dropout(dropout)
# 
#     def forward(self, x: torch.Tensor) -> torch.Tensor:
#         # Reshape to (Batch, Sequence=1, Embedding=n_qubits)
#         x_seq = x.unsqueeze(1)
# 
#         # Self-Attention + Residual 1 + LayerNorm
#         attn_out, _ = self.attention(x_seq, x_seq, x_seq)
#         x_seq = self.norm1(x_seq + self.dropout(attn_out))
# 
#         # FFN + Residual 2 + LayerNorm
#         ffn_out = self.ffn(x_seq)
#         x_seq = self.norm2(x_seq + self.dropout(ffn_out))
# 
#         # Revert to (Batch, Embedding)
#         return x_seq.squeeze(1)
# 
# 
# class FlexibleClassifierHead(nn.Module):
#     """
#     Configurable classification head with LayerNorm, GELU, and Dropout.
#     Dynamically builds hidden layers based on the requested architecture.
#     """
#     def __init__(
#         self,
#         in_features: int,
#         num_classes: int,
#         hidden_dims: Optional[List[int]] = None,
#         dropout: float = 0.3
#     ):
#         super().__init__()
# 
#         if hidden_dims is None:
#             # Default to one intermediate layer scaling down smoothly
#             hidden_dims = [in_features // 2] if in_features > 4 else []
# 
#         layers = []
#         current_dim = in_features
# 
#         for h_dim in hidden_dims:
#             if h_dim > 0:
#                 layers.extend([
#                     nn.Linear(current_dim, h_dim),
#                     nn.LayerNorm(h_dim),
#                     nn.GELU(),
#                     nn.Dropout(dropout)
#                 ])
#                 current_dim = h_dim
# 
#         # Final classification projection
#         layers.append(nn.Linear(current_dim, num_classes))
#         self.head = nn.Sequential(*layers)
# 
#     def forward(self, x: torch.Tensor) -> torch.Tensor:
#         return self.head(x)
# 
# 
# class HybridQuantumClassifier(nn.Module):
#     """
#     Advanced Hybrid Model integrating classical CNNs, self-attention, and
#     Variational Quantum Circuits (VQC). Employs skip connections to merge
#     classical and quantum logic for highly stable gradient flows.
#     """
#     def __init__(
#         self,
#         config: ModelConfig,
#         clf_hidden_dims: Optional[List[int]] = None,
#         dropout_rate: float = 0.3
#     ):
#         super().__init__()
#         self.config = config
#         logger.info("Initializing Advanced Hybrid Quantum-Classical Classifier...")
# 
#         # 1. Classical Backbone Feature Extractor
#         backbone = getattr(config, 'backbone_name', 'resnet50')
#         self.feature_extractor = ClassicalFeatureExtractor(
#             output_dim=config.n_qubits,
#             backbone_name=backbone
#         )
# 
#         # 2. Attention Bridge
#         self.attention_block = FeatureAttentionBlock(
#             embed_dim=config.n_qubits,
#             dropout=dropout_rate
#         )
# 
#         # 3. Quantum Circuit Layer
#         self.quantum_circuit = VariationalQuantumCircuit(config)
# 
#         # 4. Skip Connection Dimension Mapping
#         # We concatenate classical (attention) features and quantum features
#         combined_dim = config.n_qubits * 2
# 
#         # 5. Flexible Classification Head
#         self.classifier = FlexibleClassifierHead(
#             in_features=combined_dim,
#             num_classes=config.num_classes,
#             hidden_dims=clf_hidden_dims,
#             dropout=dropout_rate
#         )
# 
#     def forward(self, x: torch.Tensor) -> torch.Tensor:
#         """
#         Forward Pass:
#         Image -> CNN -> Attention Bridge -> VQC -> Skip Connection Concat -> Classifier
#         """
#         # Feature Extraction
#         x_c = self.feature_extractor(x)
# 
#         # Attention Mechanism (includes intrinsic residual loops)
#         x_attn = self.attention_block(x_c)
# 
#         # Quantum Processing
#         x_q = self.quantum_circuit(x_attn)
# 
#         # Skip Connection: Bypass the quantum layer with classical attention features
#         # This allows the classifier to optimally weight classical vs. quantum embeddings
#         x_skip = torch.cat([x_attn, x_q], dim=1)
# 
#         # Final Prediction
#         out = self.classifier(x_skip)
# 
#         return out