# -*- coding: utf-8 -*-
"""Training Model

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-wsp4bjp6ns9UvcPMN09uk-W1Rkem-Xk
"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile training/trainer.py
# import os
# import time
# from pathlib import Path
# from typing import Any, Dict, List, Optional, Tuple
# 
# import matplotlib.pyplot as plt
# import numpy as np
# import seaborn as sns
# import torch
# import torch.nn as nn
# import torch.optim as optim
# from sklearn.metrics import (
#     confusion_matrix,
#     f1_score,
#     precision_score,
#     recall_score,
#     roc_curve,
#     auc,
#     precision_recall_curve,
#     average_precision_score
# )
# from sklearn.preprocessing import label_binarize
# from torch.utils.tensorboard import SummaryWriter
# from torch.utils.data import DataLoader
# from tqdm import tqdm
# 
# from config.settings import ModelConfig
# from utils.logger import get_logger
# 
# logger = get_logger(__name__)
# 
# class EarlyStopping:
#     """Tracks validation loss and triggers early stopping to prevent overfitting."""
#     def __init__(self, patience: int = 5, min_delta: float = 0.0):
#         self.patience = patience
#         self.min_delta = min_delta
#         self.counter = 0
#         self.best_loss = None
#         self.early_stop = False
# 
#     def __call__(self, val_loss: float) -> bool:
#         if self.best_loss is None:
#             self.best_loss = val_loss
#         elif val_loss > self.best_loss - self.min_delta:
#             self.counter += 1
#             if self.counter >= self.patience:
#                 self.early_stop = True
#         else:
#             self.best_loss = val_loss
#             self.counter = 0
#         return self.early_stop
# 
# 
# class HybridModelTrainer:
#     """
#     Production-grade trainer with Automatic Mixed Precision (AMP), gradient clipping,
#     advanced scheduling, early stopping, TensorBoard logging, and evaluation graphing.
#     """
#     def __init__(self, model: nn.Module, config: ModelConfig, class_names: List[str] = ['Rain', 'Road', 'Sky']):
#         self.config = config
#         self.class_names = class_names
# 
#         # Automatic GPU support
#         self.device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
#         self.model = model.to(self.device)
#         logger.info(f"Trainer initialized. Target Device: {self.device}")
# 
#         # Optimization configuration
#         self.criterion = nn.CrossEntropyLoss()
#         self.optimizer = optim.AdamW(self.model.parameters(), lr=self.config.learning_rate, weight_decay=1e-4)
# 
#         # Cosine Annealing Learning Rate Scheduler
#         self.scheduler = optim.lr_scheduler.CosineAnnealingLR(
#             self.optimizer, T_max=self.config.epochs, eta_min=1e-6
#         )
# 
#         # Automatic Mixed Precision (AMP)
#         self.scaler = torch.amp.GradScaler('cuda' if torch.cuda.is_available() else 'cpu')
# 
#         # Tracking and Checkpointing
#         self.early_stopping = EarlyStopping(patience=7, min_delta=1e-4)
#         self.checkpoint_dir = Path(self.config.checkpoint_dir)
#         self.checkpoint_dir.mkdir(parents=True, exist_ok=True)
#         self.best_model_path = self.checkpoint_dir / "best_model.pt"
# 
#         # TensorBoard setup
#         self.tb_dir = Path("./assets/tensorboard_logs")
#         self.tb_dir.mkdir(parents=True, exist_ok=True)
#         self.writer = SummaryWriter(log_dir=str(self.tb_dir))
# 
#         self.start_epoch = 0
# 
#     def resume_from_checkpoint(self, path: str) -> None:
#         """Resumes training from a saved checkpoint."""
#         if not os.path.isfile(path):
#             logger.warning(f"No checkpoint found at {path}. Starting from scratch.")
#             return
# 
#         logger.info(f"Loading checkpoint from {path}")
#         checkpoint = torch.load(path, map_location=self.device)
# 
#         self.model.load_state_dict(checkpoint['model_state_dict'])
#         self.optimizer.load_state_dict(checkpoint['optimizer_state_dict'])
#         self.scheduler.load_state_dict(checkpoint['scheduler_state_dict'])
#         self.start_epoch = checkpoint['epoch'] + 1
# 
#         if 'scaler_state_dict' in checkpoint:
#             self.scaler.load_state_dict(checkpoint['scaler_state_dict'])
# 
#         logger.info(f"Successfully resumed from epoch {self.start_epoch}")
# 
#     def _save_checkpoint(self, epoch: int, val_loss: float, is_best: bool = False) -> None:
#         """Saves model state, optimizer, scheduler, and AMP scaler."""
#         state = {
#             'epoch': epoch,
#             'model_state_dict': self.model.state_dict(),
#             'optimizer_state_dict': self.optimizer.state_dict(),
#             'scheduler_state_dict': self.scheduler.state_dict(),
#             'scaler_state_dict': self.scaler.state_dict(),
#             'val_loss': val_loss
#         }
# 
#         # Save regular epoch checkpoint
#         checkpoint_path = self.checkpoint_dir / f"checkpoint_epoch_{epoch}.pt"
#         torch.save(state, checkpoint_path)
# 
#         # Overwrite best model if improved
#         if is_best:
#             torch.save(state, self.best_model_path)
#             logger.info(f"New best model saved with Val Loss: {val_loss:.4f}")
# 
#     def train_epoch(self, dataloader: DataLoader, epoch: int) -> Tuple[float, float]:
#         self.model.train()
#         running_loss = 0.0
#         correct, total = 0, 0
# 
#         pbar = tqdm(dataloader, desc=f"Epoch {epoch}/{self.config.epochs} [Train]")
#         for inputs, targets in pbar:
#             inputs, targets = inputs.to(self.device), targets.to(self.device)
# 
#             self.optimizer.zero_grad(set_to_none=True)
# 
#             # AMP Forward Pass
#             with torch.amp.autocast('cuda' if torch.cuda.is_available() else 'cpu'):
#                 outputs = self.model(inputs)
#                 loss = self.criterion(outputs, targets)
# 
#             # AMP Backward Pass & Optimization
#             self.scaler.scale(loss).backward()
# 
#             # Gradient Clipping (Unscale first)
#             self.scaler.unscale_(self.optimizer)
#             torch.nn.utils.clip_grad_norm_(self.model.parameters(), max_norm=1.0)
# 
#             self.scaler.step(self.optimizer)
#             self.scaler.update()
# 
#             running_loss += loss.item() * inputs.size(0)
#             _, predicted = outputs.max(1)
#             total += targets.size(0)
#             correct += predicted.eq(targets).sum().item()
# 
#             pbar.set_postfix({'loss': loss.item(), 'acc': correct/total})
# 
#         epoch_loss = running_loss / total
#         epoch_acc = correct / total
#         return epoch_loss, epoch_acc
# 
#     @torch.no_grad()
#     def validate_epoch(self, dataloader: DataLoader, epoch: int) -> Tuple[float, float, List[int], List[int], np.ndarray]:
#         self.model.eval()
#         running_loss = 0.0
#         correct, total = 0, 0
# 
#         all_targets = []
#         all_preds = []
#         all_probs = []
# 
#         pbar = tqdm(dataloader, desc=f"Epoch {epoch}/{self.config.epochs} [Val]")
#         for inputs, targets in pbar:
#             inputs, targets = inputs.to(self.device), targets.to(self.device)
# 
#             with torch.amp.autocast('cuda' if torch.cuda.is_available() else 'cpu'):
#                 outputs = self.model(inputs)
#                 loss = self.criterion(outputs, targets)
#                 probs = torch.softmax(outputs, dim=1)
# 
#             running_loss += loss.item() * inputs.size(0)
#             _, predicted = outputs.max(1)
#             total += targets.size(0)
#             correct += predicted.eq(targets).sum().item()
# 
#             all_targets.extend(targets.cpu().numpy())
#             all_preds.extend(predicted.cpu().numpy())
#             all_probs.append(probs.cpu().numpy())
# 
#             pbar.set_postfix({'loss': loss.item(), 'acc': correct/total})
# 
#         epoch_loss = running_loss / total
#         epoch_acc = correct / total
# 
#         return epoch_loss, epoch_acc, all_targets, all_preds, np.vstack(all_probs)
# 
#     def train(self, train_loader: DataLoader, val_loader: DataLoader) -> None:
#         """Main training loop with epoch timing, logging, and evaluation triggers."""
#         logger.info(f"Starting Training: {self.config.epochs} Epochs")
# 
#         for epoch in range(self.start_epoch, self.config.epochs + 1):
#             if epoch == 0: continue # Adjust if 1-indexed
#             start_time = time.time()
# 
#             # Train & Validate
#             train_loss, train_acc = self.train_epoch(train_loader, epoch)
#             val_loss, val_acc, val_targets, val_preds, val_probs = self.validate_epoch(val_loader, epoch)
# 
#             # LR Scheduler Step
#             self.scheduler.step()
#             current_lr = self.scheduler.get_last_lr()[0]
# 
#             # Log metrics to TensorBoard
#             self.writer.add_scalar('Loss/Train', train_loss, epoch)
#             self.writer.add_scalar('Loss/Validation', val_loss, epoch)
#             self.writer.add_scalar('Accuracy/Train', train_acc, epoch)
#             self.writer.add_scalar('Accuracy/Validation', val_acc, epoch)
#             self.writer.add_scalar('Learning_Rate', current_lr, epoch)
# 
#             time_taken = time.time() - start_time
#             logger.info(
#                 f"Epoch {epoch:03d} | Train Loss: {train_loss:.4f} | Val Loss: {val_loss:.4f} | "
#                 f"Train Acc: {train_acc:.4f} | Val Acc: {val_acc:.4f} | LR: {current_lr:.2e} | {time_taken:.1f}s"
#             )
# 
#             # Save Checkpoint & Check Best Model
#             is_best = val_loss < (self.early_stopping.best_loss or float('inf'))
#             self._save_checkpoint(epoch, val_loss, is_best)
# 
#             # Evaluate advanced metrics on best epoch
#             if is_best:
#                 self.evaluate_and_plot(val_targets, val_preds, val_probs, prefix=f"epoch_{epoch}")
# 
#             # Early Stopping Check
#             if self.early_stopping(val_loss):
#                 logger.info(f"Early stopping triggered at epoch {epoch}.")
#                 break
# 
#         self.writer.close()
#         logger.info(f"Training Complete. Best Model saved at: {self.best_model_path}")
# 
#     def evaluate_and_plot(self, y_true: List[int], y_pred: List[int], y_prob: np.ndarray, prefix: str = "final") -> None:
#         """Computes Precision, Recall, F1 and plots CM, ROC, and PR Curves."""
#         out_dir = Path("./visualization")
#         out_dir.mkdir(parents=True, exist_ok=True)
# 
#         # 1. Metrics Calculation
#         precision = precision_score(y_true, y_pred, average='weighted', zero_division=0)
#         recall = recall_score(y_true, y_pred, average='weighted', zero_division=0)
#         f1 = f1_score(y_true, y_pred, average='weighted', zero_division=0)
#         logger.info(f"--- Evaluation [{prefix}] ---")
#         logger.info(f"Precision: {precision:.4f} | Recall: {recall:.4f} | F1-Score: {f1:.4f}")
# 
#         # 2. Confusion Matrix Plot
#         cm = confusion_matrix(y_true, y_pred)
#         plt.figure(figsize=(8, 6))
#         sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', xticklabels=self.class_names, yticklabels=self.class_names)
#         plt.xlabel('Predicted Label')
#         plt.ylabel('True Label')
#         plt.title('Confusion Matrix')
#         plt.tight_layout()
#         plt.savefig(out_dir / f"confusion_matrix_{prefix}.png", dpi=300)
#         plt.close()
# 
#         # Label Binarization for Multiclass ROC & PR curves
#         y_true_bin = label_binarize(y_true, classes=[i for i in range(len(self.class_names))])
#         if y_true_bin.shape[1] == 1:
#             y_true_bin = np.hstack([1 - y_true_bin, y_true_bin])
# 
#         # 3. ROC Curve
#         plt.figure(figsize=(8, 6))
#         for i, class_name in enumerate(self.class_names):
#             fpr, tpr, _ = roc_curve(y_true_bin[:, i], y_prob[:, i])
#             roc_auc = auc(fpr, tpr)
#             plt.plot(fpr, tpr, lw=2, label=f'{class_name} (AUC = {roc_auc:.2f})')
# 
#         plt.plot([0, 1], [0, 1], color='gray', linestyle='--')
#         plt.xlim([0.0, 1.0])
#         plt.ylim([0.0, 1.05])
#         plt.xlabel('False Positive Rate')
#         plt.ylabel('True Positive Rate')
#         plt.title('Receiver Operating Characteristic (ROC)')
#         plt.legend(loc="lower right")
#         plt.grid(alpha=0.3)
#         plt.tight_layout()
#         plt.savefig(out_dir / f"roc_curve_{prefix}.png", dpi=300)
#         plt.close()
# 
#         # 4. Precision-Recall Curve
#         plt.figure(figsize=(8, 6))
#         for i, class_name in enumerate(self.class_names):
#             pr, re, _ = precision_recall_curve(y_true_bin[:, i], y_prob[:, i])
#             ap = average_precision_score(y_true_bin[:, i], y_prob[:, i])
#             plt.plot(re, pr, lw=2, label=f'{class_name} (AP = {ap:.2f})')
# 
#         plt.xlabel('Recall')
#         plt.ylabel('Precision')
#         plt.title('Precision-Recall Curve')
#         plt.legend(loc="lower left")
#         plt.grid(alpha=0.3)
#         plt.tight_layout()
#         plt.savefig(out_dir / f"pr_curve_{prefix}.png", dpi=300)
#         plt.close()